// SPDX-FileCopyrightText: 2026 The Authors
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

import "google/protobuf/timestamp.proto";

option java_package = "io.aether.android";
option java_multiple_files = true;

// Persisted state for an individual endpoint on the commissioned Matter node.
message MatterEndpoint {
  // Endpoint ID for this endpoint.
  uint32 endpoint_id = 1;
  // The list of Matter device types supported by this endpoint.
  repeated uint32 device_types = 2;

  // The label for this endpoint (fixed or user defined).
  string label = 3;

  // If endpoint supports on/off, whether the endpoint is currently on or off.
  bool on = 10;

  // Whether this endpoint exposes Level Control.
  bool supports_level_control = 12;
  // Whether this endpoint exposes Color Control color temperature attribute.
  bool supports_color_temperature = 13;
  // Level of endpoint.
  int32 level = 15;
  // Color temperature of endpoint.
  int32 color_temperature = 16;
}

// Persisted state for a commissioned Matter node.
message MatterNode {
  // Matter node ID for this commissioned device.
  uint64 node_id = 1;

  // The vendor and product for this node.
  uint32 vendor_id = 2;
  string vendor_name = 3;
  uint32 product_id = 4;
  string product_name = 5;

  // Timestamp when the node was commissioned.
  google.protobuf.Timestamp date_commissioned = 10;

  // Endpoints available on this node.
  repeated MatterEndpoint endpoints = 11;

  // The user-friendly name for this node.
  string name = 20;
  // Whether the node is online (true) or offline (false).
  bool online = 21;

}

// Persisted state for all commissioned nodes in the app fabric.
message MatterFabricState {
  repeated MatterNode nodes = 1;
}
