# SPDX-FileCopyrightText: 2026 The Authors
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = "LICENSE"
SPDX-FileCopyrightText = "2004 Apache Software Foundation"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/GoogleHomeMobileSDK.pdf"
SPDX-FileCopyrightText = "2022 Google LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gradle/wrapper/gradle-wrapper.jar"
SPDX-FileCopyrightText = "2015-2021 the original authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "app/src/main/res/drawable/emptystate_missing_content.png"
SPDX-FileCopyrightText = "2022 Google LLC"
SPDX-License-Identifier = "Apache-2.0"
