// SPDX-FileCopyrightText: 2026 The Authors
// SPDX-License-Identifier: Apache-2.0
//
// Auto-generated by matter-data-model-parser.py - do not edit.

package io.aether.android.matter

object Devices {
  object DoorLock {
    const val ID = 0x000Au
  }

  object DoorLockController {
    const val ID = 0x000Bu
  }

  object Aggregator {
    const val ID = 0x000Eu
  }

  object GenericSwitch {
    const val ID = 0x000Fu
  }

  object PowerSource {
    const val ID = 0x0011u
  }

  object OTARequestor {
    const val ID = 0x0012u
  }

  object BridgedNode {
    const val ID = 0x0013u
  }

  object OTAProvider {
    const val ID = 0x0014u
  }

  object ContactSensor {
    const val ID = 0x0015u
  }

  object RootNode {
    const val ID = 0x0016u
  }

  object SolarPower {
    const val ID = 0x0017u
  }

  object BatteryStorage {
    const val ID = 0x0018u
  }

  object SecondaryNetworkInterface {
    const val ID = 0x0019u
  }

  object Speaker {
    const val ID = 0x0022u
  }

  object CastingVideoPlayer {
    const val ID = 0x0023u
  }

  object ContentApp {
    const val ID = 0x0024u
  }

  object ModeSelect {
    const val ID = 0x0027u
  }

  object BasicVideoPlayer {
    const val ID = 0x0028u
  }

  object CastingVideoClient {
    const val ID = 0x0029u
  }

  object VideoRemoteControl {
    const val ID = 0x002Au
  }

  object Fan {
    const val ID = 0x002Bu
  }

  object AirQualitySensor {
    const val ID = 0x002Cu
  }

  object AirPurifier {
    const val ID = 0x002Du
  }

  object IrrigationSystem {
    const val ID = 0x0040u
  }

  object WaterFreezeDetector {
    const val ID = 0x0041u
  }

  object WaterValve {
    const val ID = 0x0042u
  }

  object WaterLeakDetector {
    const val ID = 0x0043u
  }

  object RainSensor {
    const val ID = 0x0044u
  }

  object SoilSensor {
    const val ID = 0x0045u
  }

  object Refrigerator {
    const val ID = 0x0070u
  }

  object TemperatureControlledCabinet {
    const val ID = 0x0071u
  }

  object RoomAirConditioner {
    const val ID = 0x0072u
  }

  object LaundryWasher {
    const val ID = 0x0073u
  }

  object RoboticVacuumCleaner {
    const val ID = 0x0074u
  }

  object Dishwasher {
    const val ID = 0x0075u
  }

  object SmokeCOAlarm {
    const val ID = 0x0076u
  }

  object CookSurface {
    const val ID = 0x0077u
  }

  object Cooktop {
    const val ID = 0x0078u
  }

  object MicrowaveOven {
    const val ID = 0x0079u
  }

  object ExtractorHood {
    const val ID = 0x007Au
  }

  object Oven {
    const val ID = 0x007Bu
  }

  object LaundryDryer {
    const val ID = 0x007Cu
  }

  object NetworkInfrastructureManager {
    const val ID = 0x0090u
  }

  object ThreadBorderRouter {
    const val ID = 0x0091u
  }

  object OnOffLight {
    const val ID = 0x0100u
  }

  object DimmableLight {
    const val ID = 0x0101u
  }

  object OnOffLightSwitch {
    const val ID = 0x0103u
  }

  object DimmerSwitch {
    const val ID = 0x0104u
  }

  object ColorDimmerSwitch {
    const val ID = 0x0105u
  }

  object LightSensor {
    const val ID = 0x0106u
  }

  object OccupancySensor {
    const val ID = 0x0107u
  }

  object OnOffPluginUnit {
    const val ID = 0x010Au
  }

  object DimmablePlugInUnit {
    const val ID = 0x010Bu
  }

  object ColorTemperatureLight {
    const val ID = 0x010Cu
  }

  object ExtendedColorLight {
    const val ID = 0x010Du
  }

  object MountedOnOffControl {
    const val ID = 0x010Fu
  }

  object MountedDimmableLoadControl {
    const val ID = 0x0110u
  }

  object JointFabricAdministrator {
    const val ID = 0x0130u
  }

  object Intercom {
    const val ID = 0x0140u
  }

  object AudioDoorbell {
    const val ID = 0x0141u
  }

  object Camera {
    const val ID = 0x0142u
  }

  object VideoDoorbell {
    const val ID = 0x0143u
  }

  object FloodlightCamera {
    const val ID = 0x0144u
  }

  object SnapshotCamera {
    const val ID = 0x0145u
  }

  object Chime {
    const val ID = 0x0146u
  }

  object CameraController {
    const val ID = 0x0147u
  }

  object Doorbell {
    const val ID = 0x0148u
  }

  object WindowCovering {
    const val ID = 0x0202u
  }

  object WindowCoveringController {
    const val ID = 0x0203u
  }

  object Closure {
    const val ID = 0x0230u
  }

  object ClosurePanel {
    const val ID = 0x0231u
  }

  object ClosureController {
    const val ID = 0x023Eu
  }

  object HeatingCoolingUnit {
    const val ID = 0x0300u
  }

  object Thermostat {
    const val ID = 0x0301u
  }

  object TemperatureSensor {
    const val ID = 0x0302u
  }

  object Pump {
    const val ID = 0x0303u
  }

  object PumpController {
    const val ID = 0x0304u
  }

  object PressureSensor {
    const val ID = 0x0305u
  }

  object FlowSensor {
    const val ID = 0x0306u
  }

  object HumiditySensor {
    const val ID = 0x0307u
  }

  object HeatPump {
    const val ID = 0x0309u
  }

  object ThermostatController {
    const val ID = 0x030Au
  }

  object EnergyEVSE {
    const val ID = 0x050Cu
  }

  object DeviceEnergyManagement {
    const val ID = 0x050Du
  }

  object WaterHeater {
    const val ID = 0x050Fu
  }

  object ElectricalSensor {
    const val ID = 0x0510u
  }

  object ElectricalUtilityMeter {
    const val ID = 0x0511u
  }

  object MeterReferencePoint {
    const val ID = 0x0512u
  }

  object ElectricalEnergyTariff {
    const val ID = 0x0513u
  }

  object ElectricalMeter {
    const val ID = 0x0514u
  }

  object ControlBridge {
    const val ID = 0x0840u
  }

  object OnOffSensor {
    const val ID = 0x0850u
  }
}

val DEVICES =
    mapOf<UInt, String>(
        Devices.DoorLock.ID to "Door Lock",
        Devices.DoorLockController.ID to "Door Lock Controller",
        Devices.Aggregator.ID to "Aggregator",
        Devices.GenericSwitch.ID to "Generic Switch",
        Devices.PowerSource.ID to "Power Source",
        Devices.OTARequestor.ID to "OTA Requestor",
        Devices.BridgedNode.ID to "Bridged Node",
        Devices.OTAProvider.ID to "OTA Provider",
        Devices.ContactSensor.ID to "Contact Sensor",
        Devices.RootNode.ID to "Root Node",
        Devices.SolarPower.ID to "Solar Power",
        Devices.BatteryStorage.ID to "Battery Storage",
        Devices.SecondaryNetworkInterface.ID to "Secondary Network Interface",
        Devices.Speaker.ID to "Speaker",
        Devices.CastingVideoPlayer.ID to "Casting Video Player",
        Devices.ContentApp.ID to "Content App",
        Devices.ModeSelect.ID to "Mode Select",
        Devices.BasicVideoPlayer.ID to "Basic Video Player",
        Devices.CastingVideoClient.ID to "Casting Video Client",
        Devices.VideoRemoteControl.ID to "Video Remote Control",
        Devices.Fan.ID to "Fan",
        Devices.AirQualitySensor.ID to "Air Quality Sensor",
        Devices.AirPurifier.ID to "Air Purifier",
        Devices.IrrigationSystem.ID to "Irrigation System",
        Devices.WaterFreezeDetector.ID to "Water Freeze Detector",
        Devices.WaterValve.ID to "Water Valve",
        Devices.WaterLeakDetector.ID to "Water Leak Detector",
        Devices.RainSensor.ID to "Rain Sensor",
        Devices.SoilSensor.ID to "Soil Sensor",
        Devices.Refrigerator.ID to "Refrigerator",
        Devices.TemperatureControlledCabinet.ID to "Temperature Controlled Cabinet",
        Devices.RoomAirConditioner.ID to "Room Air Conditioner",
        Devices.LaundryWasher.ID to "Laundry Washer",
        Devices.RoboticVacuumCleaner.ID to "Robotic Vacuum Cleaner",
        Devices.Dishwasher.ID to "Dishwasher",
        Devices.SmokeCOAlarm.ID to "Smoke CO Alarm",
        Devices.CookSurface.ID to "Cook Surface",
        Devices.Cooktop.ID to "Cooktop",
        Devices.MicrowaveOven.ID to "Microwave Oven",
        Devices.ExtractorHood.ID to "Extractor Hood",
        Devices.Oven.ID to "Oven",
        Devices.LaundryDryer.ID to "Laundry Dryer",
        Devices.NetworkInfrastructureManager.ID to "Network Infrastructure Manager",
        Devices.ThreadBorderRouter.ID to "Thread Border Router",
        Devices.OnOffLight.ID to "On/Off Light",
        Devices.DimmableLight.ID to "Dimmable Light",
        Devices.OnOffLightSwitch.ID to "On/Off Light Switch",
        Devices.DimmerSwitch.ID to "Dimmer Switch",
        Devices.ColorDimmerSwitch.ID to "Color Dimmer Switch",
        Devices.LightSensor.ID to "Light Sensor",
        Devices.OccupancySensor.ID to "Occupancy Sensor",
        Devices.OnOffPluginUnit.ID to "On/Off Plug-in Unit",
        Devices.DimmablePlugInUnit.ID to "Dimmable Plug-In Unit",
        Devices.ColorTemperatureLight.ID to "Color Temperature Light",
        Devices.ExtendedColorLight.ID to "Extended Color Light",
        Devices.MountedOnOffControl.ID to "Mounted On/Off Control",
        Devices.MountedDimmableLoadControl.ID to "Mounted Dimmable Load Control",
        Devices.JointFabricAdministrator.ID to "Joint Fabric Administrator",
        Devices.Intercom.ID to "Intercom",
        Devices.AudioDoorbell.ID to "Audio Doorbell",
        Devices.Camera.ID to "Camera",
        Devices.VideoDoorbell.ID to "Video Doorbell",
        Devices.FloodlightCamera.ID to "Floodlight Camera",
        Devices.SnapshotCamera.ID to "Snapshot Camera",
        Devices.Chime.ID to "Chime",
        Devices.CameraController.ID to "Camera Controller",
        Devices.Doorbell.ID to "Doorbell",
        Devices.WindowCovering.ID to "Window Covering",
        Devices.WindowCoveringController.ID to "Window Covering Controller",
        Devices.Closure.ID to "Closure",
        Devices.ClosurePanel.ID to "Closure Panel",
        Devices.ClosureController.ID to "Closure Controller",
        Devices.HeatingCoolingUnit.ID to "Heating/Cooling Unit",
        Devices.Thermostat.ID to "Thermostat",
        Devices.TemperatureSensor.ID to "Temperature Sensor",
        Devices.Pump.ID to "Pump",
        Devices.PumpController.ID to "Pump Controller",
        Devices.PressureSensor.ID to "Pressure Sensor",
        Devices.FlowSensor.ID to "Flow Sensor",
        Devices.HumiditySensor.ID to "Humidity Sensor",
        Devices.HeatPump.ID to "Heat Pump",
        Devices.ThermostatController.ID to "Thermostat Controller",
        Devices.EnergyEVSE.ID to "Energy EVSE",
        Devices.DeviceEnergyManagement.ID to "Device Energy Management",
        Devices.WaterHeater.ID to "Water Heater",
        Devices.ElectricalSensor.ID to "Electrical Sensor",
        Devices.ElectricalUtilityMeter.ID to "Electrical Utility Meter",
        Devices.MeterReferencePoint.ID to "Meter Reference Point",
        Devices.ElectricalEnergyTariff.ID to "Electrical Energy Tariff",
        Devices.ElectricalMeter.ID to "Electrical Meter",
        Devices.ControlBridge.ID to "Control Bridge",
        Devices.OnOffSensor.ID to "On/Off Sensor",
    )
