// SPDX-FileCopyrightText: 2026 The Authors
// SPDX-License-Identifier: Apache-2.0
//
// Auto-generated by matter-data-model-parser.py - do not edit.

package io.aether.android.matter

object Enums {
  enum class ACLClusterAuthMode(val value: UInt) {
    PASE(1u),
    CASE(2u),
    Group(3u),
  }

  enum class ACLClusterChangeType(val value: UInt) {
    Changed(0u),
    Added(1u),
    Removed(2u),
  }

  enum class ACLClusterPrivilege(val value: UInt) {
    View(1u),
    ProxyView(2u),
    Operate(3u),
    Manage(4u),
    Administer(5u),
  }

  enum class ActionsClusterActionError(val value: UInt) {
    Unknown(0u),
    Interrupted(1u),
  }

  enum class ActionsClusterActionState(val value: UInt) {
    Inactive(0u),
    Active(1u),
    Paused(2u),
    Disabled(3u),
  }

  enum class ActionsClusterActionType(val value: UInt) {
    Other(0u),
    Scene(1u),
    Sequence(2u),
    Automation(3u),
    Exception(4u),
    Notification(5u),
    Alarm(6u),
  }

  enum class ActionsClusterEndpointListType(val value: UInt) {
    Other(0u),
    Room(1u),
    Zone(2u),
  }

  enum class AdminCommissioningClusterCommissioningWindowStatus(val value: UInt) {
    WindowNotOpen(0u),
    EnhancedWindowOpen(1u),
    BasicWindowOpen(2u),
  }

  enum class AirQualityClusterAirQuality(val value: UInt) {
    Unknown(0u),
    Good(1u),
    Fair(2u),
    Moderate(3u),
    Poor(4u),
    VeryPoor(5u),
    ExtremelyPoor(6u),
  }

  enum class ApplicationBasicClusterApplicationStatus(val value: UInt) {
    STOPPED(0u),
    ACTIVE_VISIBLE_FOCUS(1u),
    ACTIVE_HIDDEN(2u),
    ACTIVE_VISIBLE_NOT_FOCUS(3u),
  }

  enum class AudioOutputClusterOutputType(val value: UInt) {
    HDMI(0u),
    BT(1u),
    OPTICAL(2u),
    HEADPHONE(3u),
    INTERNAL(4u),
    OTHER(5u),
  }

  enum class CameraAVSettingsUserLevelManagementClusterPhysicalMovement(val value: UInt) {
    Idle(0u),
    Moving(1u),
  }

  enum class CameraAVStreamManagementClusterAudioCodec(val value: UInt) {
    OPUS(0u),
    AACLC(1u),
  }

  enum class CameraAVStreamManagementClusterImageCodec(val value: UInt) {
    JPEG(0u),
  }

  enum class CameraAVStreamManagementClusterTriStateAuto(val value: UInt) {
    Off(0u),
    On(1u),
    Auto(2u),
  }

  enum class CameraAVStreamManagementClusterTwoWayTalkSupportType(val value: UInt) {
    NotSupported(0u),
    HalfDuplex(1u),
    FullDuplex(2u),
  }

  enum class CameraAVStreamManagementClusterVideoCodec(val value: UInt) {
    H264(0u),
    HEVC(1u),
    VVC(2u),
    AV1(3u),
  }

  enum class ChannelClusterLineupInfoType(val value: UInt) {
    MSO(0u),
  }

  enum class ClosureControlClusterClosureError(val value: UInt) {
    PhysicallyBlocked(0u),
    BlockedBySensor(1u),
    TemperatureLimited(2u),
    MaintenanceRequired(3u),
    InternalInterference(4u),
  }

  enum class ClosureControlClusterCurrentPosition(val value: UInt) {
    FullyClosed(0u),
    FullyOpened(1u),
    PartiallyOpened(2u),
    OpenedForPedestrian(3u),
    OpenedForVentilation(4u),
    OpenedAtSignature(5u),
  }

  enum class ClosureControlClusterMainState(val value: UInt) {
    Stopped(0u),
    Moving(1u),
    WaitingForMotion(2u),
    Error(3u),
    Calibrating(4u),
    Protected(5u),
    Disengaged(6u),
    SetupRequired(7u),
  }

  enum class ClosureControlClusterTargetPosition(val value: UInt) {
    MoveToFullyClosed(0u),
    MoveToFullyOpen(1u),
    MoveToPedestrianPosition(2u),
    MoveToVentilationPosition(3u),
    MoveToSignaturePosition(4u),
  }

  enum class ClosureDimensionClusterClosureUnit(val value: UInt) {
    Millimeter(0u),
    Degree(1u),
  }

  enum class ClosureDimensionClusterModulationType(val value: UInt) {
    SlatsOrientation(0u),
    SlatsOpenwork(1u),
    StripesAlignment(2u),
    Opacity(3u),
    Ventilation(4u),
  }

  enum class ClosureDimensionClusterOverflow(val value: UInt) {
    NoOverflow(0u),
    Inside(1u),
    Outside(2u),
    TopInside(3u),
    TopOutside(4u),
    BottomInside(5u),
    BottomOutside(6u),
    LeftInside(7u),
    LeftOutside(8u),
    RightInside(9u),
    RightOutside(10u),
  }

  enum class ClosureDimensionClusterRotationAxis(val value: UInt) {
    Left(0u),
    CenteredVertical(1u),
    LeftAndRight(2u),
    Right(3u),
    Top(4u),
    CenteredHorizontal(5u),
    TopAndBottom(6u),
    Bottom(7u),
    LeftBarrier(8u),
    LeftAndRightBarriers(9u),
    RightBarrier(10u),
  }

  enum class ClosureDimensionClusterStepDirection(val value: UInt) {
    Decrease(0u),
    Increase(1u),
  }

  enum class ClosureDimensionClusterTranslationDirection(val value: UInt) {
    Downward(0u),
    Upward(1u),
    VerticalMask(2u),
    VerticalSymmetry(3u),
    Leftward(4u),
    Rightward(5u),
    HorizontalMask(6u),
    HorizontalSymmetry(7u),
    Forward(8u),
    Backward(9u),
    DepthMask(10u),
    DepthSymmetry(11u),
  }

  enum class CommodityTariffClusterAuxiliaryLoadSetting(val value: UInt) {
    Off(0u),
    On(1u),
    None(2u),
  }

  enum class CommodityTariffClusterBlockMode(val value: UInt) {
    NoBlock(0u),
    Combined(1u),
    Individual(2u),
  }

  enum class CommodityTariffClusterDayEntryRandomizationType(val value: UInt) {
    None(0u),
    Fixed(1u),
    Random(2u),
    RandomPositive(3u),
    RandomNegative(4u),
  }

  enum class CommodityTariffClusterDayType(val value: UInt) {
    Standard(0u),
    Holiday(1u),
    Dynamic(2u),
    Event(3u),
  }

  enum class CommodityTariffClusterPeakPeriodSeverity(val value: UInt) {
    Unused(0u),
    Low(1u),
    Medium(2u),
    High(3u),
  }

  enum class ConcentrationMeasurementClusterLevelValue(val value: UInt) {
    Unknown(0u),
    Low(1u),
    Medium(2u),
    High(3u),
    Critical(4u),
  }

  enum class ConcentrationMeasurementClusterMeasurementMedium(val value: UInt) {
    Air(0u),
    Water(1u),
    Soil(2u),
  }

  enum class ConcentrationMeasurementClusterMeasurementUnit(val value: UInt) {
    PPM(0u),
    PPB(1u),
    PPT(2u),
    MGM3(3u),
    UGM3(4u),
    NGM3(5u),
    PM3(6u),
    BQM3(7u),
  }

  enum class ContentAppObserverClusterStatus(val value: UInt) {
    Success(0u),
    UnexpectedData(1u),
  }

  enum class ContentLauncherClusterMetricType(val value: UInt) {
    Pixels(0u),
    Percentage(1u),
  }

  enum class ContentLauncherClusterParameter(val value: UInt) {
    Actor(0u),
    Channel(1u),
    Character(2u),
    Director(3u),
    Event(4u),
    Franchise(5u),
    Genre(6u),
    League(7u),
    Popularity(8u),
    Provider(9u),
    Sport(10u),
    SportsTeam(11u),
    Type(12u),
    Video(13u),
  }

  enum class DeviceEnergyManagementClusterAdjustmentCause(val value: UInt) {
    LocalOptimization(0u),
    GridOptimization(1u),
  }

  enum class DeviceEnergyManagementClusterCause(val value: UInt) {
    NormalCompletion(0u),
    Offline(1u),
    Fault(2u),
    UserOptOut(3u),
    Cancelled(4u),
  }

  enum class DeviceEnergyManagementClusterCostType(val value: UInt) {
    Financial(0u),
    GHGEmissions(1u),
    Comfort(2u),
    Temperature(3u),
  }

  enum class DeviceEnergyManagementClusterESAState(val value: UInt) {
    Offline(0u),
    Online(1u),
    Fault(2u),
    PowerAdjustActive(3u),
    Paused(4u),
  }

  enum class DeviceEnergyManagementClusterESAType(val value: UInt) {
    EVSE(0u),
    SpaceHeating(1u),
    WaterHeating(2u),
    SpaceCooling(3u),
    SpaceHeatingCooling(4u),
    BatteryStorage(5u),
    SolarPV(6u),
    FridgeFreezer(7u),
    WashingMachine(8u),
    Dishwasher(9u),
    Cooking(10u),
    HomeWaterPump(11u),
    IrrigationWaterPump(12u),
    PoolPump(13u),
    Other(255u),
  }

  enum class DeviceEnergyManagementClusterForecastUpdateReason(val value: UInt) {
    InternalOptimization(0u),
    LocalOptimization(1u),
    GridOptimization(2u),
  }

  enum class DeviceEnergyManagementClusterOptOutState(val value: UInt) {
    NoOptOut(0u),
    LocalOptOut(1u),
    GridOptOut(2u),
    OptOut(3u),
  }

  enum class DiagnosticLogsClusterIntent(val value: UInt) {
    EndUserSupport(0u),
    NetworkDiag(1u),
    CrashLogs(2u),
  }

  enum class DiagnosticLogsClusterStatus(val value: UInt) {
    Success(0u),
    Exhausted(1u),
    NoLogs(2u),
    Busy(3u),
    Denied(4u),
  }

  enum class DiagnosticLogsClusterTransferProtocol(val value: UInt) {
    ResponsePayload(0u),
    BDX(1u),
  }

  enum class DiagnosticsEthernetClusterPHYRate(val value: UInt) {
    Rate10M(0u),
    Rate100M(1u),
    Rate1G(2u),
    Rate2_5G(3u),
    Rate5G(4u),
    Rate10G(5u),
    Rate40G(6u),
    Rate100G(7u),
    Rate200G(8u),
    Rate400G(9u),
  }

  enum class DiagnosticsGeneralClusterBootReason(val value: UInt) {
    Unspecified(0u),
    PowerOnReboot(1u),
    BrownOutReset(2u),
    SoftwareWatchdogReset(3u),
    HardwareWatchdogReset(4u),
    SoftwareUpdateCompleted(5u),
    SoftwareReset(6u),
  }

  enum class DiagnosticsGeneralClusterHardwareFault(val value: UInt) {
    Unspecified(0u),
    Radio(1u),
    Sensor(2u),
    ResettableOverTemp(3u),
    NonResettableOverTemp(4u),
    PowerSource(5u),
    VisualDisplayFault(6u),
    AudioOutputFault(7u),
    UserInterfaceFault(8u),
    NonVolatileMemoryError(9u),
    TamperDetected(10u),
  }

  enum class DiagnosticsGeneralClusterInterfaceType(val value: UInt) {
    Unspecified(0u),
    WiFi(1u),
    Ethernet(2u),
    Cellular(3u),
    Thread(4u),
  }

  enum class DiagnosticsGeneralClusterNetworkFault(val value: UInt) {
    Unspecified(0u),
    HardwareFailure(1u),
    NetworkJammed(2u),
    ConnectionFailed(3u),
  }

  enum class DiagnosticsGeneralClusterRadioFault(val value: UInt) {
    Unspecified(0u),
    WiFiFault(1u),
    CellularFault(2u),
    ThreadFault(3u),
    NFCFault(4u),
    BLEFault(5u),
    EthernetFault(6u),
  }

  enum class DiagnosticsThreadClusterNetworkFault(val value: UInt) {
    Unspecified(0u),
    LinkDown(1u),
    HardwareFailure(2u),
    NetworkJammed(3u),
  }

  enum class DiagnosticsThreadClusterRoutingRole(val value: UInt) {
    Unspecified(0u),
    Unassigned(1u),
    SleepyEndDevice(2u),
    EndDevice(3u),
    REED(4u),
    Router(5u),
    Leader(6u),
  }

  enum class DiagnosticsWiFiClusterAssociationFailureCause(val value: UInt) {
    Unknown(0u),
    AssociationFailed(1u),
    AuthenticationFailed(2u),
    SsidNotFound(3u),
  }

  enum class DiagnosticsWiFiClusterConnectionStatus(val value: UInt) {
    Connected(0u),
    NotConnected(1u),
  }

  enum class DiagnosticsWiFiClusterSecurityType(val value: UInt) {
    Unspecified(0u),
    None(1u),
    WEP(2u),
    WPA(3u),
    WPA2(4u),
    WPA3(5u),
  }

  enum class DiagnosticsWiFiClusterWiFiVersion(val value: UInt) {
    A(0u),
    B(1u),
    G(2u),
    N(3u),
    Ac(4u),
    Ax(5u),
  }

  enum class DoorLockClusterAlarmCode(val value: UInt) {
    LockJammed(0u),
    LockFactoryReset(1u),
    LockRadioPowerCycled(3u),
    WrongCodeEntryLimit(4u),
    FrontEsceutcheonRemoved(5u),
    DoorForcedOpen(6u),
    DoorAjar(7u),
    ForcedUser(8u),
  }

  enum class DoorLockClusterCredentialRule(val value: UInt) {
    Single(0u),
    Dual(1u),
    Tri(2u),
  }

  enum class DoorLockClusterCredentialType(val value: UInt) {
    ProgrammingPIN(0u),
    PIN(1u),
    RFID(2u),
    Fingerprint(3u),
    FingerVein(4u),
    Face(5u),
  }

  enum class DoorLockClusterDataOperationType(val value: UInt) {
    Add(0u),
    Clear(1u),
    Modify(2u),
  }

  enum class DoorLockClusterDoorState(val value: UInt) {
    DoorOpen(0u),
    DoorClosed(1u),
    DoorJammed(2u),
    DoorForcedOpen(3u),
    DoorUnspecifiedError(4u),
    DoorAjar(5u),
  }

  enum class DoorLockClusterLockDataType(val value: UInt) {
    Unspecified(0u),
    ProgrammingCode(1u),
    UserIndex(2u),
    WeekDaySchedule(3u),
    YearDaySchedule(4u),
    HolidaySchedule(5u),
    PIN(6u),
    RFID(7u),
    Fingerprint(8u),
    FingerVein(9u),
    Face(10u),
  }

  enum class DoorLockClusterLockOperationType(val value: UInt) {
    Lock(0u),
    Unlock(1u),
    NonAccessUserEvent(2u),
    ForcedUserEvent(3u),
  }

  enum class DoorLockClusterOperatingMode(val value: UInt) {
    Normal(0u),
    Vacation(1u),
    Privacy(2u),
    NoRemoteLockUnlock(3u),
    Passage(4u),
  }

  enum class DoorLockClusterOperationError(val value: UInt) {
    Unspecified(0u),
    InvalidCredential(1u),
    DisabledUserDenied(2u),
    Restricted(3u),
    InsufficientBattery(4u),
  }

  enum class DoorLockClusterOperationSource(val value: UInt) {
    Unspecified(0u),
    Manual(1u),
    ProprietaryRemote(2u),
    Keypad(3u),
    Auto(4u),
    Button(5u),
    Schedule(6u),
    Remote(7u),
    RFID(8u),
    Biometric(9u),
  }

  enum class DoorLockClusterUserStatus(val value: UInt) {
    Available(0u),
    OccupiedEnabled(1u),
    OccupiedDisabled(3u),
  }

  enum class DoorLockClusterUserType(val value: UInt) {
    UnrestrictedUser(0u),
    YearDayScheduleUser(1u),
    WeekDayScheduleUser(2u),
    ProgrammingUser(3u),
    NonAccessUser(4u),
    ForcedUser(5u),
    DisposableUser(6u),
    ExpiringUser(7u),
    ScheduleRestrictedUser(8u),
    RemoteOnlyUser(9u),
  }

  enum class ElectricalGridConditionsClusterThreeLevel(val value: UInt) {
    Low(0u),
    Medium(1u),
    High(2u),
  }

  enum class ElectricalPowerMeasurementClusterPowerMode(val value: UInt) {
    Unknown(0u),
    DC(1u),
    AC(2u),
  }

  enum class EnergyEVSEClusterEnergyTransferStoppedReason(val value: UInt) {
    EVStopped(0u),
    EVSEStopped(1u),
    Other(2u),
  }

  enum class EnergyEVSEClusterFaultState(val value: UInt) {
    NoError(0u),
    MeterFailure(1u),
    OverVoltage(2u),
    UnderVoltage(3u),
    OverCurrent(4u),
    ContactWetFailure(5u),
    ContactDryFailure(6u),
    GroundFault(7u),
    PowerLoss(8u),
    PowerQuality(9u),
    PilotShortCircuit(10u),
    EmergencyStop(11u),
    EVDisconnected(12u),
    WrongPowerSupply(13u),
    LiveNeutralSwap(14u),
    OverTemperature(15u),
    Other(255u),
  }

  enum class EnergyEVSEClusterState(val value: UInt) {
    NotPluggedIn(0u),
    PluggedInNoDemand(1u),
    PluggedInDemand(2u),
    PluggedInCharging(3u),
    PluggedInDischarging(4u),
    SessionEnding(5u),
    Fault(6u),
  }

  enum class EnergyEVSEClusterSupplyState(val value: UInt) {
    Disabled(0u),
    ChargingEnabled(1u),
    DischargingEnabled(2u),
    DisabledError(3u),
    DisabledDiagnostics(4u),
  }

  enum class EnergyPreferenceClusterEnergyPriority(val value: UInt) {
    Comfort(0u),
    Speed(1u),
    Efficiency(2u),
    WaterConsumption(3u),
  }

  enum class GeneralCommissioningClusterCommissioningError(val value: UInt) {
    OK(0u),
    ValueOutsideRange(1u),
    InvalidAuthentication(2u),
    NoFailSafe(3u),
    BusyWithOtherAdmin(4u),
  }

  enum class GeneralCommissioningClusterRegulatoryLocationType(val value: UInt) {
    Indoor(0u),
    Outdoor(1u),
    IndoorOutdoor(2u),
  }

  enum class GroupKeyManagementClusterGroupKeyMulticastPolicy(val value: UInt) {
    PerGroupID(0u),
    AllNodes(1u),
  }

  enum class GroupKeyManagementClusterGroupKeySecurityPolicy(val value: UInt) {
    TrustFirst(0u),
    CacheAndSync(1u),
  }

  enum class GroupcastClusterGroupcastTestResult(val value: UInt) {
    Success(0u),
    GeneralError(1u),
    MessageReplay(2u),
    FailedAuth(3u),
    NoAvailableKey(4u),
    SendFailure(5u),
  }

  enum class GroupcastClusterGroupcastTesting(val value: UInt) {
    DisableTesting(0u),
    EnableListenerTesting(1u),
    EnableSenderTesting(2u),
  }

  enum class GroupcastClusterMulticastAddrPolicy(val value: UInt) {
    IanaAddr(0u),
    PerGroup(1u),
  }

  enum class JointFabricDatastoreClusterDatastoreState(val value: UInt) {
    Pending(0u),
    Committed(1u),
    DeletePending(2u),
  }

  enum class JointFabricPKIClusterICACSigningRequestStatus(val value: UInt) {
    OK(0u),
    InvalidIcaCsrFormat(1u),
    InvalidIcaCsrSignature(2u),
    FailedDCLVendorIdValidation(3u),
    NotAnIcac(4u),
    BusyAnchorTransfer(5u),
    IcaCsrSigningFailed(6u),
    IcaCsrRequestNoUserConsent(7u),
  }

  enum class JointFabricPKIClusterTransferAnchorResponseStatus(val value: UInt) {
    OK(0u),
    TransferAnchorStatusDatastoreBusy(1u),
    TransferAnchorStatusNoUserConsent(2u),
  }

  enum class LaundryDryerControlsClusterDrynessLevel(val value: UInt) {
    Low(0u),
    Normal(1u),
    Extra(2u),
    Max(3u),
  }

  enum class LaundryWasherControlsClusterNumberOfRinses(val value: UInt) {
    None(0u),
    Normal(1u),
    Extra(2u),
    Max(3u),
  }

  enum class LocalizationTimeFormatClusterCalendarType(val value: UInt) {
    Buddhist(0u),
    Chinese(1u),
    Coptic(2u),
    Ethiopian(3u),
    Gregorian(4u),
    Hebrew(5u),
    Indian(6u),
    Islamic(7u),
    Japanese(8u),
    Korean(9u),
    Persian(10u),
    Taiwanese(11u),
  }

  enum class LocalizationTimeFormatClusterHourFormat(val value: UInt) {
    `12hr`(0u),
    `24hr`(1u),
  }

  enum class LocalizationUnitClusterTempUnit(val value: UInt) {
    Fahrenheit(0u),
    Celsius(1u),
    Kelvin(2u),
  }

  enum class MediaInputClusterInputType(val value: UInt) {
    INTERNAL(0u),
    AUX(1u),
    COAX(2u),
    COMPOSITE(3u),
    HDMI(4u),
    INPUT(5u),
    LINE(6u),
    OPTICAL(7u),
    VIDEO(8u),
    SCART(9u),
    USB(10u),
    OTHER(11u),
  }

  enum class MediaPlaybackClusterPlaybackState(val value: UInt) {
    PLAYING(0u),
    PAUSED(1u),
    NOT_PLAYING(2u),
    BUFFERING(3u),
  }

  enum class MessagesClusterFutureMessagePreference(val value: UInt) {
    Allowed(0u),
    Increased(1u),
    Reduced(2u),
    Disallowed(3u),
    Banned(4u),
  }

  enum class MessagesClusterMessagePriority(val value: UInt) {
    Low(0u),
    Medium(1u),
    High(2u),
    Critical(3u),
  }

  enum class MeterIdentificationClusterMeterType(val value: UInt) {
    Utility(0u),
    Private(1u),
    Generic(2u),
  }

  enum class Mode_WaterHeaterClusterModeTag(val value: UInt) {
    Auto(0u),
    Quick(1u),
    Quiet(2u),
    LowNoise(3u),
    LowEnergy(4u),
    Vacation(5u),
    Min(6u),
    Max(7u),
    Night(8u),
    Day(9u),
    Off(16384u),
    Manual(16385u),
    Timed(16386u),
  }

  enum class NetworkCommissioningClusterNetworkCommissioningStatus(val value: UInt) {
    Success(0u),
    OutOfRange(1u),
    BoundsExceeded(2u),
    NetworkIDNotFound(3u),
    DuplicateNetworkID(4u),
    NetworkNotFound(5u),
    RegulatoryError(6u),
    AuthFailure(7u),
    UnsupportedSecurity(8u),
    OtherConnectionFailure(9u),
    IPV6Failed(10u),
    IPBindFailed(11u),
    UnknownError(12u),
  }

  enum class NetworkCommissioningClusterWiFiBand(val value: UInt) {}

  enum class OTAProviderClusterApplyUpdateAction(val value: UInt) {
    Proceed(0u),
    AwaitNextAction(1u),
    Discontinue(2u),
  }

  enum class OTAProviderClusterDownloadProtocol(val value: UInt) {
    BDXSynchronous(0u),
    BDXAsynchronous(1u),
    HTTPS(2u),
    VendorSpecific(3u),
  }

  enum class OTARequestorClusterAnnouncementReason(val value: UInt) {
    SimpleAnnouncement(0u),
    UpdateAvailable(1u),
    UrgentUpdateAvailable(2u),
  }

  enum class OTARequestorClusterChangeReason(val value: UInt) {
    Unknown(0u),
    Success(1u),
    Failure(2u),
    TimeOut(3u),
    DelayByProvider(4u),
  }

  enum class OTARequestorClusterUpdateState(val value: UInt) {
    Unknown(0u),
    Idle(1u),
    Querying(2u),
    DelayedOnQuery(3u),
    Downloading(4u),
    Applying(5u),
    DelayedOnApply(6u),
    RollingBack(7u),
    DelayedOnUserConsent(8u),
  }

  enum class OnOffClusterStartUpOnOff(val value: UInt) {
    Off(0u),
    On(1u),
    Toggle(2u),
  }

  enum class OperationalCredentialClusterCertificateChainType(val value: UInt) {
    DACCertificate(1u),
    PAICertificate(2u),
  }

  enum class OperationalCredentialClusterNodeOperationalCertStatus(val value: UInt) {
    Ok(0u),
    InvalidPublicKey(1u),
    InvalidNodeOpId(2u),
    InvalidNOC(3u),
    MissingCsr(4u),
    TableFull(5u),
    InvalidAdminSubject(6u),
    FabricConflict(9u),
    LabelConflict(10u),
    InvalidFabricIndex(11u),
  }

  enum class OperationalStateClusterErrorStateIDGeneralErrorsRange(val value: UInt) {
    NoError(0u),
    UnableToStartOrResume(1u),
    UnableToCompleteOperation(2u),
    CommandInvalidInState(3u),
  }

  enum class OperationalStateClusterErrorStateIDRanges(val value: UInt) {}

  enum class OperationalState_RVCClusterErrorState(val value: UInt) {
    FailedToFindChargingDock(64u),
    Stuck(65u),
    DustBinMissing(66u),
    DustBinFull(67u),
    WaterTankEmpty(68u),
    WaterTankMissing(69u),
    WaterTankLidOpen(70u),
    MopCleaningPadMissing(71u),
  }

  enum class OperationalState_RVCClusterOperationalState(val value: UInt) {
    SeekingCharger(64u),
    Charging(65u),
    Docked(66u),
  }

  enum class PowerSourceClusterBatApprovedChemistry(val value: UInt) {
    Unspecified(0u),
    Alkaline(1u),
    LithiumCarbonFluoride(2u),
    LithiumChromiumOxide(3u),
    LithiumCopperOxide(4u),
    LithiumIronDisulfide(5u),
    LithiumManganeseDioxide(6u),
    LithiumThionylChloride(7u),
    Magnesium(8u),
    MercuryOxide(9u),
    NickelOxyhydride(10u),
    SilverOxide(11u),
    ZincAir(12u),
    ZincCarbon(13u),
    ZincChloride(14u),
    ZincManganeseDioxide(15u),
    LeadAcid(16u),
    LithiumCobaltOxide(17u),
    LithiumIon(18u),
    LithiumIonPolymer(19u),
    LithiumIronPhosphate(20u),
    LithiumSulfur(21u),
    LithiumTitanate(22u),
    NickelCadmium(23u),
    NickelHydrogen(24u),
    NickelIron(25u),
    NickelMetalHydride(26u),
    NickelZinc(27u),
    SilverZinc(28u),
    SodiumIon(29u),
    SodiumSulfur(30u),
    ZincBromide(31u),
    ZincCerium(32u),
  }

  enum class PowerSourceClusterBatChargeFault(val value: UInt) {
    Unspecified(0u),
    AmbientTooHot(1u),
    AmbientTooCold(2u),
    BatteryTooHot(3u),
    BatteryTooCold(4u),
    BatteryAbsent(5u),
    BatteryOverVoltage(6u),
    BatteryUnderVoltage(7u),
    ChargerOverVoltage(8u),
    ChargerUnderVoltage(9u),
    SafetyTimeout(10u),
  }

  enum class PowerSourceClusterBatChargeLevel(val value: UInt) {
    OK(0u),
    Warning(1u),
    Critical(2u),
  }

  enum class PowerSourceClusterBatChargeState(val value: UInt) {
    Unknown(0u),
    IsCharging(1u),
    IsAtFullCharge(2u),
    IsNotCharging(3u),
  }

  enum class PowerSourceClusterBatCommonDesignation(val value: UInt) {
    Unspecified(0u),
    AAA(1u),
    AA(2u),
    C(3u),
    D(4u),
    `4v5`(5u),
    `6v0`(6u),
    `9v0`(7u),
    `1_2AA`(8u),
    AAAA(9u),
    A(10u),
    B(11u),
    F(12u),
    N(13u),
    No6(14u),
    SubC(15u),
    A23(16u),
    A27(17u),
    BA5800(18u),
    Duplex(19u),
    `4SR44`(20u),
    `523`(21u),
    `531`(22u),
    `15v0`(23u),
    `22v5`(24u),
    `30v0`(25u),
    `45v0`(26u),
    `67v5`(27u),
    J(28u),
    CR123A(29u),
    CR2(30u),
    `2CR5`(31u),
    CR_P2(32u),
    CR_V3(33u),
    SR41(34u),
    SR43(35u),
    SR44(36u),
    SR45(37u),
    SR48(38u),
    SR54(39u),
    SR55(40u),
    SR57(41u),
    SR58(42u),
    SR59(43u),
    SR60(44u),
    SR63(45u),
    SR64(46u),
    SR65(47u),
    SR66(48u),
    SR67(49u),
    SR68(50u),
    SR69(51u),
    SR516(52u),
    SR731(53u),
    SR712(54u),
    LR932(55u),
    A5(56u),
    A10(57u),
    A13(58u),
    A312(59u),
    A675(60u),
    AC41E(61u),
    `10180`(62u),
    `10280`(63u),
    `10440`(64u),
    `14250`(65u),
    `14430`(66u),
    `14500`(67u),
    `14650`(68u),
    `15270`(69u),
    `16340`(70u),
    RCR123A(71u),
    `17500`(72u),
    `17670`(73u),
    `18350`(74u),
    `18500`(75u),
    `18650`(76u),
    `19670`(77u),
    `25500`(78u),
    `26650`(79u),
    `32600`(80u),
  }

  enum class PowerSourceClusterBatFault(val value: UInt) {
    Unspecified(0u),
    OverTemp(1u),
    UnderTemp(2u),
  }

  enum class PowerSourceClusterBatReplaceability(val value: UInt) {
    Unspecified(0u),
    NotReplaceable(1u),
    UserReplaceable(2u),
    FactoryReplaceable(3u),
  }

  enum class PowerSourceClusterPowerSourceStatus(val value: UInt) {
    Unspecified(0u),
    Active(1u),
    Standby(2u),
    Unavailable(3u),
  }

  enum class PowerSourceClusterWiredCurrentType(val value: UInt) {
    AC(0u),
    DC(1u),
  }

  enum class PowerSourceClusterWiredFault(val value: UInt) {
    Unspecified(0u),
    OverVoltage(1u),
    UnderVoltage(2u),
  }

  enum class PumpConfigurationControlClusterControlModeAttribute(val value: UInt) {
    ConstantSpeed(0u),
    ConstantPressure(1u),
    ProportionalPressure(2u),
    ConstantFlow(3u),
    ConstantTemperature(5u),
    Automatic(7u),
  }

  enum class PumpConfigurationControlClusterOperationModeAttribute(val value: UInt) {
    Normal(0u),
    Minimum(1u),
    Maximum(2u),
    Local(3u),
  }

  enum class PushAVStreamTransportClusterCMAFInterface(val value: UInt) {
    Interface1(0u),
    Interface2DASH(1u),
    Interface2HLS(2u),
  }

  enum class PushAVStreamTransportClusterContainerFormat(val value: UInt) {
    CMAF(0u),
  }

  enum class PushAVStreamTransportClusterIngestMethods(val value: UInt) {
    CMAFIngest(0u),
  }

  enum class PushAVStreamTransportClusterTransportStatus(val value: UInt) {
    Active(0u),
    Inactive(1u),
  }

  enum class PushAVStreamTransportClusterTransportTriggerType(val value: UInt) {
    Command(0u),
    Motion(1u),
    Continuous(2u),
  }

  enum class PushAVStreamTransportClusterTriggerActivationReason(val value: UInt) {
    UserInitiated(0u),
    Automation(1u),
    Emergency(2u),
  }

  enum class ResourceMonitoringClusterChangeIndication(val value: UInt) {
    OK(0u),
    Warning(1u),
    Critical(2u),
  }

  enum class ResourceMonitoringClusterDegradationDirection(val value: UInt) {
    Up(0u),
    Down(1u),
  }

  enum class ResourceMonitoringClusterProductIdentifierType(val value: UInt) {
    UPC(0u),
    GTIN8(1u),
    EAN(2u),
    GTIN14(3u),
    OEM(4u),
  }

  enum class ServiceAreaClusterOperationalStatus(val value: UInt) {
    Pending(0u),
    Operating(1u),
    Skipped(2u),
    Completed(3u),
  }

  enum class ServiceAreaClusterSelectAreasStatus(val value: UInt) {
    Success(0u),
    UnsupportedArea(1u),
    InvalidInMode(2u),
    InvalidSet(3u),
  }

  enum class ServiceAreaClusterSkipAreaStatus(val value: UInt) {
    Success(0u),
    InvalidAreaList(1u),
    InvalidInMode(2u),
    InvalidSkippedArea(3u),
  }

  enum class SmokeCOAlarmClusterAlarmState(val value: UInt) {
    Normal(0u),
    Warning(1u),
    Critical(2u),
  }

  enum class SmokeCOAlarmClusterContaminationState(val value: UInt) {
    Normal(0u),
    Low(1u),
    Warning(2u),
    Critical(3u),
  }

  enum class SmokeCOAlarmClusterEndOfService(val value: UInt) {
    Normal(0u),
    Expired(1u),
  }

  enum class SmokeCOAlarmClusterExpressedState(val value: UInt) {
    Normal(0u),
    SmokeAlarm(1u),
    COAlarm(2u),
    BatteryAlert(3u),
    Testing(4u),
    HardwareFault(5u),
    EndOfService(6u),
    InterconnectSmoke(7u),
    InterconnectCO(8u),
  }

  enum class SmokeCOAlarmClusterMuteState(val value: UInt) {
    NotMuted(0u),
    Muted(1u),
  }

  enum class SmokeCOAlarmClusterSensitivity(val value: UInt) {
    High(0u),
    Standard(1u),
    Low(2u),
  }

  enum class TLSClientManagementClusterStatusCode(val value: UInt) {
    EndpointAlreadyInstalled(2u),
    RootCertificateNotFound(3u),
    ClientCertificateNotFound(4u),
    EndpointInUse(5u),
    InvalidTime(6u),
  }

  enum class TimeSyncClusterGranularity(val value: UInt) {
    NoTimeGranularity(0u),
    MinutesGranularity(1u),
    SecondsGranularity(2u),
    MillisecondsGranularity(3u),
    MicrosecondsGranularity(4u),
  }

  enum class TimeSyncClusterTimeSource(val value: UInt) {
    None(0u),
    Unknown(1u),
    Admin(2u),
    NodeTimeCluster(3u),
    NonFabricSntp(4u),
    NonFabricNtp(5u),
    FabricSntp(6u),
    FabricNtp(7u),
    MixedNtp(8u),
    NonFabricSntpNts(9u),
    NonFabricNtpNts(10u),
    FabricSntpNts(11u),
    FabricNtpNts(12u),
    MixedNtpNts(13u),
    CloudSource(14u),
    Ptp(15u),
    Gnss(16u),
  }

  enum class ValveConfigurationControlClusterValveState(val value: UInt) {
    Closed(0u),
    Open(1u),
    Transitioning(2u),
  }

  enum class WaterHeaterManagementClusterBoostState(val value: UInt) {
    Inactive(0u),
    Active(1u),
  }

  enum class ZoneManagementClusterZoneEventStoppedReason(val value: UInt) {
    ActionStopped(0u),
    Timeout(1u),
  }

  enum class ZoneManagementClusterZoneEventTriggeredReason(val value: UInt) {
    Motion(0u),
  }

  enum class ZoneManagementClusterZoneSource(val value: UInt) {
    Mfg(0u),
    User(1u),
  }

  enum class ZoneManagementClusterZoneType(val value: UInt) {
    TwoDCARTZone(0u),
  }

  enum class ZoneManagementClusterZoneUse(val value: UInt) {
    Motion(0u),
    Privacy(1u),
    Focus(2u),
  }
}
