// SPDX-FileCopyrightText: 2026 The Authors
// SPDX-License-Identifier: Apache-2.0
//
// Auto-generated by matter-data-model-parser.py - do not edit.

package io.aether.android.matter

object Enums {
  enum class ACLClusterAuthMode(val value: Int) {
    PASE(1),
    CASE(2),
    Group(3),
  }

  enum class ACLClusterChangeType(val value: Int) {
    Changed(0),
    Added(1),
    Removed(2),
  }

  enum class ACLClusterPrivilege(val value: Int) {
    View(1),
    ProxyView(2),
    Operate(3),
    Manage(4),
    Administer(5),
  }

  enum class ActionsClusterActionError(val value: Int) {
    Unknown(0),
    Interrupted(1),
  }

  enum class ActionsClusterActionState(val value: Int) {
    Inactive(0),
    Active(1),
    Paused(2),
    Disabled(3),
  }

  enum class ActionsClusterActionType(val value: Int) {
    Other(0),
    Scene(1),
    Sequence(2),
    Automation(3),
    Exception(4),
    Notification(5),
    Alarm(6),
  }

  enum class ActionsClusterEndpointListType(val value: Int) {
    Other(0),
    Room(1),
    Zone(2),
  }

  enum class AdminCommissioningClusterCommissioningWindowStatus(val value: Int) {
    WindowNotOpen(0),
    EnhancedWindowOpen(1),
    BasicWindowOpen(2),
  }

  enum class AirQualityClusterAirQuality(val value: Int) {
    Unknown(0),
    Good(1),
    Fair(2),
    Moderate(3),
    Poor(4),
    VeryPoor(5),
    ExtremelyPoor(6),
  }

  enum class ApplicationBasicClusterApplicationStatus(val value: Int) {
    STOPPED(0),
    ACTIVE_VISIBLE_FOCUS(1),
    ACTIVE_HIDDEN(2),
    ACTIVE_VISIBLE_NOT_FOCUS(3),
  }

  enum class AudioOutputClusterOutputType(val value: Int) {
    HDMI(0),
    BT(1),
    OPTICAL(2),
    HEADPHONE(3),
    INTERNAL(4),
    OTHER(5),
  }

  enum class CameraAVSettingsUserLevelManagementClusterPhysicalMovement(val value: Int) {
    Idle(0),
    Moving(1),
  }

  enum class CameraAVStreamManagementClusterAudioCodec(val value: Int) {
    OPUS(0),
    AACLC(1),
  }

  enum class CameraAVStreamManagementClusterImageCodec(val value: Int) {
    JPEG(0),
  }

  enum class CameraAVStreamManagementClusterTriStateAuto(val value: Int) {
    Off(0),
    On(1),
    Auto(2),
  }

  enum class CameraAVStreamManagementClusterTwoWayTalkSupportType(val value: Int) {
    NotSupported(0),
    HalfDuplex(1),
    FullDuplex(2),
  }

  enum class CameraAVStreamManagementClusterVideoCodec(val value: Int) {
    H264(0),
    HEVC(1),
    VVC(2),
    AV1(3),
  }

  enum class ChannelClusterLineupInfoType(val value: Int) {
    MSO(0),
  }

  enum class ClosureControlClusterClosureError(val value: Int) {
    PhysicallyBlocked(0),
    BlockedBySensor(1),
    TemperatureLimited(2),
    MaintenanceRequired(3),
    InternalInterference(4),
  }

  enum class ClosureControlClusterCurrentPosition(val value: Int) {
    FullyClosed(0),
    FullyOpened(1),
    PartiallyOpened(2),
    OpenedForPedestrian(3),
    OpenedForVentilation(4),
    OpenedAtSignature(5),
  }

  enum class ClosureControlClusterMainState(val value: Int) {
    Stopped(0),
    Moving(1),
    WaitingForMotion(2),
    Error(3),
    Calibrating(4),
    Protected(5),
    Disengaged(6),
    SetupRequired(7),
  }

  enum class ClosureControlClusterTargetPosition(val value: Int) {
    MoveToFullyClosed(0),
    MoveToFullyOpen(1),
    MoveToPedestrianPosition(2),
    MoveToVentilationPosition(3),
    MoveToSignaturePosition(4),
  }

  enum class ClosureDimensionClusterClosureUnit(val value: Int) {
    Millimeter(0),
    Degree(1),
  }

  enum class ClosureDimensionClusterModulationType(val value: Int) {
    SlatsOrientation(0),
    SlatsOpenwork(1),
    StripesAlignment(2),
    Opacity(3),
    Ventilation(4),
  }

  enum class ClosureDimensionClusterOverflow(val value: Int) {
    NoOverflow(0),
    Inside(1),
    Outside(2),
    TopInside(3),
    TopOutside(4),
    BottomInside(5),
    BottomOutside(6),
    LeftInside(7),
    LeftOutside(8),
    RightInside(9),
    RightOutside(10),
  }

  enum class ClosureDimensionClusterRotationAxis(val value: Int) {
    Left(0),
    CenteredVertical(1),
    LeftAndRight(2),
    Right(3),
    Top(4),
    CenteredHorizontal(5),
    TopAndBottom(6),
    Bottom(7),
    LeftBarrier(8),
    LeftAndRightBarriers(9),
    RightBarrier(10),
  }

  enum class ClosureDimensionClusterStepDirection(val value: Int) {
    Decrease(0),
    Increase(1),
  }

  enum class ClosureDimensionClusterTranslationDirection(val value: Int) {
    Downward(0),
    Upward(1),
    VerticalMask(2),
    VerticalSymmetry(3),
    Leftward(4),
    Rightward(5),
    HorizontalMask(6),
    HorizontalSymmetry(7),
    Forward(8),
    Backward(9),
    DepthMask(10),
    DepthSymmetry(11),
  }

  enum class CommodityTariffClusterAuxiliaryLoadSetting(val value: Int) {
    Off(0),
    On(1),
    None(2),
  }

  enum class CommodityTariffClusterBlockMode(val value: Int) {
    NoBlock(0),
    Combined(1),
    Individual(2),
  }

  enum class CommodityTariffClusterDayEntryRandomizationType(val value: Int) {
    None(0),
    Fixed(1),
    Random(2),
    RandomPositive(3),
    RandomNegative(4),
  }

  enum class CommodityTariffClusterDayType(val value: Int) {
    Standard(0),
    Holiday(1),
    Dynamic(2),
    Event(3),
  }

  enum class CommodityTariffClusterPeakPeriodSeverity(val value: Int) {
    Unused(0),
    Low(1),
    Medium(2),
    High(3),
  }

  enum class ConcentrationMeasurementClusterLevelValue(val value: Int) {
    Unknown(0),
    Low(1),
    Medium(2),
    High(3),
    Critical(4),
  }

  enum class ConcentrationMeasurementClusterMeasurementMedium(val value: Int) {
    Air(0),
    Water(1),
    Soil(2),
  }

  enum class ConcentrationMeasurementClusterMeasurementUnit(val value: Int) {
    PPM(0),
    PPB(1),
    PPT(2),
    MGM3(3),
    UGM3(4),
    NGM3(5),
    PM3(6),
    BQM3(7),
  }

  enum class ContentAppObserverClusterStatus(val value: Int) {
    Success(0),
    UnexpectedData(1),
  }

  enum class ContentLauncherClusterMetricType(val value: Int) {
    Pixels(0),
    Percentage(1),
  }

  enum class ContentLauncherClusterParameter(val value: Int) {
    Actor(0),
    Channel(1),
    Character(2),
    Director(3),
    Event(4),
    Franchise(5),
    Genre(6),
    League(7),
    Popularity(8),
    Provider(9),
    Sport(10),
    SportsTeam(11),
    Type(12),
    Video(13),
  }

  enum class DeviceEnergyManagementClusterAdjustmentCause(val value: Int) {
    LocalOptimization(0),
    GridOptimization(1),
  }

  enum class DeviceEnergyManagementClusterCause(val value: Int) {
    NormalCompletion(0),
    Offline(1),
    Fault(2),
    UserOptOut(3),
    Cancelled(4),
  }

  enum class DeviceEnergyManagementClusterCostType(val value: Int) {
    Financial(0),
    GHGEmissions(1),
    Comfort(2),
    Temperature(3),
  }

  enum class DeviceEnergyManagementClusterESAState(val value: Int) {
    Offline(0),
    Online(1),
    Fault(2),
    PowerAdjustActive(3),
    Paused(4),
  }

  enum class DeviceEnergyManagementClusterESAType(val value: Int) {
    EVSE(0),
    SpaceHeating(1),
    WaterHeating(2),
    SpaceCooling(3),
    SpaceHeatingCooling(4),
    BatteryStorage(5),
    SolarPV(6),
    FridgeFreezer(7),
    WashingMachine(8),
    Dishwasher(9),
    Cooking(10),
    HomeWaterPump(11),
    IrrigationWaterPump(12),
    PoolPump(13),
    Other(255),
  }

  enum class DeviceEnergyManagementClusterForecastUpdateReason(val value: Int) {
    InternalOptimization(0),
    LocalOptimization(1),
    GridOptimization(2),
  }

  enum class DeviceEnergyManagementClusterOptOutState(val value: Int) {
    NoOptOut(0),
    LocalOptOut(1),
    GridOptOut(2),
    OptOut(3),
  }

  enum class DiagnosticLogsClusterIntent(val value: Int) {
    EndUserSupport(0),
    NetworkDiag(1),
    CrashLogs(2),
  }

  enum class DiagnosticLogsClusterStatus(val value: Int) {
    Success(0),
    Exhausted(1),
    NoLogs(2),
    Busy(3),
    Denied(4),
  }

  enum class DiagnosticLogsClusterTransferProtocol(val value: Int) {
    ResponsePayload(0),
    BDX(1),
  }

  enum class DiagnosticsEthernetClusterPHYRate(val value: Int) {
    Rate10M(0),
    Rate100M(1),
    Rate1G(2),
    Rate2_5G(3),
    Rate5G(4),
    Rate10G(5),
    Rate40G(6),
    Rate100G(7),
    Rate200G(8),
    Rate400G(9),
  }

  enum class DiagnosticsGeneralClusterBootReason(val value: Int) {
    Unspecified(0),
    PowerOnReboot(1),
    BrownOutReset(2),
    SoftwareWatchdogReset(3),
    HardwareWatchdogReset(4),
    SoftwareUpdateCompleted(5),
    SoftwareReset(6),
  }

  enum class DiagnosticsGeneralClusterHardwareFault(val value: Int) {
    Unspecified(0),
    Radio(1),
    Sensor(2),
    ResettableOverTemp(3),
    NonResettableOverTemp(4),
    PowerSource(5),
    VisualDisplayFault(6),
    AudioOutputFault(7),
    UserInterfaceFault(8),
    NonVolatileMemoryError(9),
    TamperDetected(10),
  }

  enum class DiagnosticsGeneralClusterInterfaceType(val value: Int) {
    Unspecified(0),
    WiFi(1),
    Ethernet(2),
    Cellular(3),
    Thread(4),
  }

  enum class DiagnosticsGeneralClusterNetworkFault(val value: Int) {
    Unspecified(0),
    HardwareFailure(1),
    NetworkJammed(2),
    ConnectionFailed(3),
  }

  enum class DiagnosticsGeneralClusterRadioFault(val value: Int) {
    Unspecified(0),
    WiFiFault(1),
    CellularFault(2),
    ThreadFault(3),
    NFCFault(4),
    BLEFault(5),
    EthernetFault(6),
  }

  enum class DiagnosticsThreadClusterNetworkFault(val value: Int) {
    Unspecified(0),
    LinkDown(1),
    HardwareFailure(2),
    NetworkJammed(3),
  }

  enum class DiagnosticsThreadClusterRoutingRole(val value: Int) {
    Unspecified(0),
    Unassigned(1),
    SleepyEndDevice(2),
    EndDevice(3),
    REED(4),
    Router(5),
    Leader(6),
  }

  enum class DiagnosticsWiFiClusterAssociationFailureCause(val value: Int) {
    Unknown(0),
    AssociationFailed(1),
    AuthenticationFailed(2),
    SsidNotFound(3),
  }

  enum class DiagnosticsWiFiClusterConnectionStatus(val value: Int) {
    Connected(0),
    NotConnected(1),
  }

  enum class DiagnosticsWiFiClusterSecurityType(val value: Int) {
    Unspecified(0),
    None(1),
    WEP(2),
    WPA(3),
    WPA2(4),
    WPA3(5),
  }

  enum class DiagnosticsWiFiClusterWiFiVersion(val value: Int) {
    A(0),
    B(1),
    G(2),
    N(3),
    Ac(4),
    Ax(5),
  }

  enum class DoorLockClusterAlarmCode(val value: Int) {
    LockJammed(0),
    LockFactoryReset(1),
    LockRadioPowerCycled(3),
    WrongCodeEntryLimit(4),
    FrontEsceutcheonRemoved(5),
    DoorForcedOpen(6),
    DoorAjar(7),
    ForcedUser(8),
  }

  enum class DoorLockClusterCredentialRule(val value: Int) {
    Single(0),
    Dual(1),
    Tri(2),
  }

  enum class DoorLockClusterCredentialType(val value: Int) {
    ProgrammingPIN(0),
    PIN(1),
    RFID(2),
    Fingerprint(3),
    FingerVein(4),
    Face(5),
  }

  enum class DoorLockClusterDataOperationType(val value: Int) {
    Add(0),
    Clear(1),
    Modify(2),
  }

  enum class DoorLockClusterDoorState(val value: Int) {
    DoorOpen(0),
    DoorClosed(1),
    DoorJammed(2),
    DoorForcedOpen(3),
    DoorUnspecifiedError(4),
    DoorAjar(5),
  }

  enum class DoorLockClusterLockDataType(val value: Int) {
    Unspecified(0),
    ProgrammingCode(1),
    UserIndex(2),
    WeekDaySchedule(3),
    YearDaySchedule(4),
    HolidaySchedule(5),
    PIN(6),
    RFID(7),
    Fingerprint(8),
    FingerVein(9),
    Face(10),
  }

  enum class DoorLockClusterLockOperationType(val value: Int) {
    Lock(0),
    Unlock(1),
    NonAccessUserEvent(2),
    ForcedUserEvent(3),
  }

  enum class DoorLockClusterOperatingMode(val value: Int) {
    Normal(0),
    Vacation(1),
    Privacy(2),
    NoRemoteLockUnlock(3),
    Passage(4),
  }

  enum class DoorLockClusterOperationError(val value: Int) {
    Unspecified(0),
    InvalidCredential(1),
    DisabledUserDenied(2),
    Restricted(3),
    InsufficientBattery(4),
  }

  enum class DoorLockClusterOperationSource(val value: Int) {
    Unspecified(0),
    Manual(1),
    ProprietaryRemote(2),
    Keypad(3),
    Auto(4),
    Button(5),
    Schedule(6),
    Remote(7),
    RFID(8),
    Biometric(9),
  }

  enum class DoorLockClusterUserStatus(val value: Int) {
    Available(0),
    OccupiedEnabled(1),
    OccupiedDisabled(3),
  }

  enum class DoorLockClusterUserType(val value: Int) {
    UnrestrictedUser(0),
    YearDayScheduleUser(1),
    WeekDayScheduleUser(2),
    ProgrammingUser(3),
    NonAccessUser(4),
    ForcedUser(5),
    DisposableUser(6),
    ExpiringUser(7),
    ScheduleRestrictedUser(8),
    RemoteOnlyUser(9),
  }

  enum class ElectricalGridConditionsClusterThreeLevel(val value: Int) {
    Low(0),
    Medium(1),
    High(2),
  }

  enum class ElectricalPowerMeasurementClusterPowerMode(val value: Int) {
    Unknown(0),
    DC(1),
    AC(2),
  }

  enum class EnergyEVSEClusterEnergyTransferStoppedReason(val value: Int) {
    EVStopped(0),
    EVSEStopped(1),
    Other(2),
  }

  enum class EnergyEVSEClusterFaultState(val value: Int) {
    NoError(0),
    MeterFailure(1),
    OverVoltage(2),
    UnderVoltage(3),
    OverCurrent(4),
    ContactWetFailure(5),
    ContactDryFailure(6),
    GroundFault(7),
    PowerLoss(8),
    PowerQuality(9),
    PilotShortCircuit(10),
    EmergencyStop(11),
    EVDisconnected(12),
    WrongPowerSupply(13),
    LiveNeutralSwap(14),
    OverTemperature(15),
    Other(255),
  }

  enum class EnergyEVSEClusterState(val value: Int) {
    NotPluggedIn(0),
    PluggedInNoDemand(1),
    PluggedInDemand(2),
    PluggedInCharging(3),
    PluggedInDischarging(4),
    SessionEnding(5),
    Fault(6),
  }

  enum class EnergyEVSEClusterSupplyState(val value: Int) {
    Disabled(0),
    ChargingEnabled(1),
    DischargingEnabled(2),
    DisabledError(3),
    DisabledDiagnostics(4),
  }

  enum class EnergyPreferenceClusterEnergyPriority(val value: Int) {
    Comfort(0),
    Speed(1),
    Efficiency(2),
    WaterConsumption(3),
  }

  enum class GeneralCommissioningClusterCommissioningError(val value: Int) {
    OK(0),
    ValueOutsideRange(1),
    InvalidAuthentication(2),
    NoFailSafe(3),
    BusyWithOtherAdmin(4),
  }

  enum class GeneralCommissioningClusterRegulatoryLocationType(val value: Int) {
    Indoor(0),
    Outdoor(1),
    IndoorOutdoor(2),
  }

  enum class GroupKeyManagementClusterGroupKeyMulticastPolicy(val value: Int) {
    PerGroupID(0),
    AllNodes(1),
  }

  enum class GroupKeyManagementClusterGroupKeySecurityPolicy(val value: Int) {
    TrustFirst(0),
    CacheAndSync(1),
  }

  enum class GroupcastClusterGroupcastTestResult(val value: Int) {
    Success(0),
    GeneralError(1),
    MessageReplay(2),
    FailedAuth(3),
    NoAvailableKey(4),
    SendFailure(5),
  }

  enum class GroupcastClusterGroupcastTesting(val value: Int) {
    DisableTesting(0),
    EnableListenerTesting(1),
    EnableSenderTesting(2),
  }

  enum class GroupcastClusterMulticastAddrPolicy(val value: Int) {
    IanaAddr(0),
    PerGroup(1),
  }

  enum class JointFabricDatastoreClusterDatastoreState(val value: Int) {
    Pending(0),
    Committed(1),
    DeletePending(2),
  }

  enum class JointFabricPKIClusterICACSigningRequestStatus(val value: Int) {
    OK(0),
    InvalidIcaCsrFormat(1),
    InvalidIcaCsrSignature(2),
    FailedDCLVendorIdValidation(3),
    NotAnIcac(4),
    BusyAnchorTransfer(5),
    IcaCsrSigningFailed(6),
    IcaCsrRequestNoUserConsent(7),
  }

  enum class JointFabricPKIClusterTransferAnchorResponseStatus(val value: Int) {
    OK(0),
    TransferAnchorStatusDatastoreBusy(1),
    TransferAnchorStatusNoUserConsent(2),
  }

  enum class LaundryDryerControlsClusterDrynessLevel(val value: Int) {
    Low(0),
    Normal(1),
    Extra(2),
    Max(3),
  }

  enum class LaundryWasherControlsClusterNumberOfRinses(val value: Int) {
    None(0),
    Normal(1),
    Extra(2),
    Max(3),
  }

  enum class LocalizationTimeFormatClusterCalendarType(val value: Int) {
    Buddhist(0),
    Chinese(1),
    Coptic(2),
    Ethiopian(3),
    Gregorian(4),
    Hebrew(5),
    Indian(6),
    Islamic(7),
    Japanese(8),
    Korean(9),
    Persian(10),
    Taiwanese(11),
  }

  enum class LocalizationTimeFormatClusterHourFormat(val value: Int) {
    `12hr`(0),
    `24hr`(1),
  }

  enum class LocalizationUnitClusterTempUnit(val value: Int) {
    Fahrenheit(0),
    Celsius(1),
    Kelvin(2),
  }

  enum class MediaInputClusterInputType(val value: Int) {
    INTERNAL(0),
    AUX(1),
    COAX(2),
    COMPOSITE(3),
    HDMI(4),
    INPUT(5),
    LINE(6),
    OPTICAL(7),
    VIDEO(8),
    SCART(9),
    USB(10),
    OTHER(11),
  }

  enum class MediaPlaybackClusterPlaybackState(val value: Int) {
    PLAYING(0),
    PAUSED(1),
    NOT_PLAYING(2),
    BUFFERING(3),
  }

  enum class MessagesClusterFutureMessagePreference(val value: Int) {
    Allowed(0),
    Increased(1),
    Reduced(2),
    Disallowed(3),
    Banned(4),
  }

  enum class MessagesClusterMessagePriority(val value: Int) {
    Low(0),
    Medium(1),
    High(2),
    Critical(3),
  }

  enum class MeterIdentificationClusterMeterType(val value: Int) {
    Utility(0),
    Private(1),
    Generic(2),
  }

  enum class Mode_WaterHeaterClusterModeTag(val value: Int) {
    Auto(0),
    Quick(1),
    Quiet(2),
    LowNoise(3),
    LowEnergy(4),
    Vacation(5),
    Min(6),
    Max(7),
    Night(8),
    Day(9),
    Off(16384),
    Manual(16385),
    Timed(16386),
  }

  enum class NetworkCommissioningClusterNetworkCommissioningStatus(val value: Int) {
    Success(0),
    OutOfRange(1),
    BoundsExceeded(2),
    NetworkIDNotFound(3),
    DuplicateNetworkID(4),
    NetworkNotFound(5),
    RegulatoryError(6),
    AuthFailure(7),
    UnsupportedSecurity(8),
    OtherConnectionFailure(9),
    IPV6Failed(10),
    IPBindFailed(11),
    UnknownError(12),
  }

  enum class NetworkCommissioningClusterWiFiBand(val value: Int) {}

  enum class OTAProviderClusterApplyUpdateAction(val value: Int) {
    Proceed(0),
    AwaitNextAction(1),
    Discontinue(2),
  }

  enum class OTAProviderClusterDownloadProtocol(val value: Int) {
    BDXSynchronous(0),
    BDXAsynchronous(1),
    HTTPS(2),
    VendorSpecific(3),
  }

  enum class OTARequestorClusterAnnouncementReason(val value: Int) {
    SimpleAnnouncement(0),
    UpdateAvailable(1),
    UrgentUpdateAvailable(2),
  }

  enum class OTARequestorClusterChangeReason(val value: Int) {
    Unknown(0),
    Success(1),
    Failure(2),
    TimeOut(3),
    DelayByProvider(4),
  }

  enum class OTARequestorClusterUpdateState(val value: Int) {
    Unknown(0),
    Idle(1),
    Querying(2),
    DelayedOnQuery(3),
    Downloading(4),
    Applying(5),
    DelayedOnApply(6),
    RollingBack(7),
    DelayedOnUserConsent(8),
  }

  enum class OnOffClusterStartUpOnOff(val value: Int) {
    Off(0),
    On(1),
    Toggle(2),
  }

  enum class OperationalCredentialClusterCertificateChainType(val value: Int) {
    DACCertificate(1),
    PAICertificate(2),
  }

  enum class OperationalCredentialClusterNodeOperationalCertStatus(val value: Int) {
    Ok(0),
    InvalidPublicKey(1),
    InvalidNodeOpId(2),
    InvalidNOC(3),
    MissingCsr(4),
    TableFull(5),
    InvalidAdminSubject(6),
    FabricConflict(9),
    LabelConflict(10),
    InvalidFabricIndex(11),
  }

  enum class OperationalStateClusterErrorStateIDGeneralErrorsRange(val value: Int) {
    NoError(0),
    UnableToStartOrResume(1),
    UnableToCompleteOperation(2),
    CommandInvalidInState(3),
  }

  enum class OperationalStateClusterErrorStateIDRanges(val value: Int) {}

  enum class OperationalState_RVCClusterErrorState(val value: Int) {
    FailedToFindChargingDock(64),
    Stuck(65),
    DustBinMissing(66),
    DustBinFull(67),
    WaterTankEmpty(68),
    WaterTankMissing(69),
    WaterTankLidOpen(70),
    MopCleaningPadMissing(71),
  }

  enum class OperationalState_RVCClusterOperationalState(val value: Int) {
    SeekingCharger(64),
    Charging(65),
    Docked(66),
  }

  enum class PowerSourceClusterBatApprovedChemistry(val value: Int) {
    Unspecified(0),
    Alkaline(1),
    LithiumCarbonFluoride(2),
    LithiumChromiumOxide(3),
    LithiumCopperOxide(4),
    LithiumIronDisulfide(5),
    LithiumManganeseDioxide(6),
    LithiumThionylChloride(7),
    Magnesium(8),
    MercuryOxide(9),
    NickelOxyhydride(10),
    SilverOxide(11),
    ZincAir(12),
    ZincCarbon(13),
    ZincChloride(14),
    ZincManganeseDioxide(15),
    LeadAcid(16),
    LithiumCobaltOxide(17),
    LithiumIon(18),
    LithiumIonPolymer(19),
    LithiumIronPhosphate(20),
    LithiumSulfur(21),
    LithiumTitanate(22),
    NickelCadmium(23),
    NickelHydrogen(24),
    NickelIron(25),
    NickelMetalHydride(26),
    NickelZinc(27),
    SilverZinc(28),
    SodiumIon(29),
    SodiumSulfur(30),
    ZincBromide(31),
    ZincCerium(32),
  }

  enum class PowerSourceClusterBatChargeFault(val value: Int) {
    Unspecified(0),
    AmbientTooHot(1),
    AmbientTooCold(2),
    BatteryTooHot(3),
    BatteryTooCold(4),
    BatteryAbsent(5),
    BatteryOverVoltage(6),
    BatteryUnderVoltage(7),
    ChargerOverVoltage(8),
    ChargerUnderVoltage(9),
    SafetyTimeout(10),
  }

  enum class PowerSourceClusterBatChargeLevel(val value: Int) {
    OK(0),
    Warning(1),
    Critical(2),
  }

  enum class PowerSourceClusterBatChargeState(val value: Int) {
    Unknown(0),
    IsCharging(1),
    IsAtFullCharge(2),
    IsNotCharging(3),
  }

  enum class PowerSourceClusterBatCommonDesignation(val value: Int) {
    Unspecified(0),
    AAA(1),
    AA(2),
    C(3),
    D(4),
    `4v5`(5),
    `6v0`(6),
    `9v0`(7),
    `1_2AA`(8),
    AAAA(9),
    A(10),
    B(11),
    F(12),
    N(13),
    No6(14),
    SubC(15),
    A23(16),
    A27(17),
    BA5800(18),
    Duplex(19),
    `4SR44`(20),
    `523`(21),
    `531`(22),
    `15v0`(23),
    `22v5`(24),
    `30v0`(25),
    `45v0`(26),
    `67v5`(27),
    J(28),
    CR123A(29),
    CR2(30),
    `2CR5`(31),
    CR_P2(32),
    CR_V3(33),
    SR41(34),
    SR43(35),
    SR44(36),
    SR45(37),
    SR48(38),
    SR54(39),
    SR55(40),
    SR57(41),
    SR58(42),
    SR59(43),
    SR60(44),
    SR63(45),
    SR64(46),
    SR65(47),
    SR66(48),
    SR67(49),
    SR68(50),
    SR69(51),
    SR516(52),
    SR731(53),
    SR712(54),
    LR932(55),
    A5(56),
    A10(57),
    A13(58),
    A312(59),
    A675(60),
    AC41E(61),
    `10180`(62),
    `10280`(63),
    `10440`(64),
    `14250`(65),
    `14430`(66),
    `14500`(67),
    `14650`(68),
    `15270`(69),
    `16340`(70),
    RCR123A(71),
    `17500`(72),
    `17670`(73),
    `18350`(74),
    `18500`(75),
    `18650`(76),
    `19670`(77),
    `25500`(78),
    `26650`(79),
    `32600`(80),
  }

  enum class PowerSourceClusterBatFault(val value: Int) {
    Unspecified(0),
    OverTemp(1),
    UnderTemp(2),
  }

  enum class PowerSourceClusterBatReplaceability(val value: Int) {
    Unspecified(0),
    NotReplaceable(1),
    UserReplaceable(2),
    FactoryReplaceable(3),
  }

  enum class PowerSourceClusterPowerSourceStatus(val value: Int) {
    Unspecified(0),
    Active(1),
    Standby(2),
    Unavailable(3),
  }

  enum class PowerSourceClusterWiredCurrentType(val value: Int) {
    AC(0),
    DC(1),
  }

  enum class PowerSourceClusterWiredFault(val value: Int) {
    Unspecified(0),
    OverVoltage(1),
    UnderVoltage(2),
  }

  enum class PumpConfigurationControlClusterControlModeAttribute(val value: Int) {
    ConstantSpeed(0),
    ConstantPressure(1),
    ProportionalPressure(2),
    ConstantFlow(3),
    ConstantTemperature(5),
    Automatic(7),
  }

  enum class PumpConfigurationControlClusterOperationModeAttribute(val value: Int) {
    Normal(0),
    Minimum(1),
    Maximum(2),
    Local(3),
  }

  enum class PushAVStreamTransportClusterCMAFInterface(val value: Int) {
    Interface1(0),
    Interface2DASH(1),
    Interface2HLS(2),
  }

  enum class PushAVStreamTransportClusterContainerFormat(val value: Int) {
    CMAF(0),
  }

  enum class PushAVStreamTransportClusterIngestMethods(val value: Int) {
    CMAFIngest(0),
  }

  enum class PushAVStreamTransportClusterTransportStatus(val value: Int) {
    Active(0),
    Inactive(1),
  }

  enum class PushAVStreamTransportClusterTransportTriggerType(val value: Int) {
    Command(0),
    Motion(1),
    Continuous(2),
  }

  enum class PushAVStreamTransportClusterTriggerActivationReason(val value: Int) {
    UserInitiated(0),
    Automation(1),
    Emergency(2),
  }

  enum class ResourceMonitoringClusterChangeIndication(val value: Int) {
    OK(0),
    Warning(1),
    Critical(2),
  }

  enum class ResourceMonitoringClusterDegradationDirection(val value: Int) {
    Up(0),
    Down(1),
  }

  enum class ResourceMonitoringClusterProductIdentifierType(val value: Int) {
    UPC(0),
    GTIN8(1),
    EAN(2),
    GTIN14(3),
    OEM(4),
  }

  enum class ServiceAreaClusterOperationalStatus(val value: Int) {
    Pending(0),
    Operating(1),
    Skipped(2),
    Completed(3),
  }

  enum class ServiceAreaClusterSelectAreasStatus(val value: Int) {
    Success(0),
    UnsupportedArea(1),
    InvalidInMode(2),
    InvalidSet(3),
  }

  enum class ServiceAreaClusterSkipAreaStatus(val value: Int) {
    Success(0),
    InvalidAreaList(1),
    InvalidInMode(2),
    InvalidSkippedArea(3),
  }

  enum class SmokeCOAlarmClusterAlarmState(val value: Int) {
    Normal(0),
    Warning(1),
    Critical(2),
  }

  enum class SmokeCOAlarmClusterContaminationState(val value: Int) {
    Normal(0),
    Low(1),
    Warning(2),
    Critical(3),
  }

  enum class SmokeCOAlarmClusterEndOfService(val value: Int) {
    Normal(0),
    Expired(1),
  }

  enum class SmokeCOAlarmClusterExpressedState(val value: Int) {
    Normal(0),
    SmokeAlarm(1),
    COAlarm(2),
    BatteryAlert(3),
    Testing(4),
    HardwareFault(5),
    EndOfService(6),
    InterconnectSmoke(7),
    InterconnectCO(8),
  }

  enum class SmokeCOAlarmClusterMuteState(val value: Int) {
    NotMuted(0),
    Muted(1),
  }

  enum class SmokeCOAlarmClusterSensitivity(val value: Int) {
    High(0),
    Standard(1),
    Low(2),
  }

  enum class TLSClientManagementClusterStatusCode(val value: Int) {
    EndpointAlreadyInstalled(2),
    RootCertificateNotFound(3),
    ClientCertificateNotFound(4),
    EndpointInUse(5),
    InvalidTime(6),
  }

  enum class TimeSyncClusterGranularity(val value: Int) {
    NoTimeGranularity(0),
    MinutesGranularity(1),
    SecondsGranularity(2),
    MillisecondsGranularity(3),
    MicrosecondsGranularity(4),
  }

  enum class TimeSyncClusterTimeSource(val value: Int) {
    None(0),
    Unknown(1),
    Admin(2),
    NodeTimeCluster(3),
    NonFabricSntp(4),
    NonFabricNtp(5),
    FabricSntp(6),
    FabricNtp(7),
    MixedNtp(8),
    NonFabricSntpNts(9),
    NonFabricNtpNts(10),
    FabricSntpNts(11),
    FabricNtpNts(12),
    MixedNtpNts(13),
    CloudSource(14),
    Ptp(15),
    Gnss(16),
  }

  enum class ValveConfigurationControlClusterValveState(val value: Int) {
    Closed(0),
    Open(1),
    Transitioning(2),
  }

  enum class WaterHeaterManagementClusterBoostState(val value: Int) {
    Inactive(0),
    Active(1),
  }

  enum class ZoneManagementClusterZoneEventStoppedReason(val value: Int) {
    ActionStopped(0),
    Timeout(1),
  }

  enum class ZoneManagementClusterZoneEventTriggeredReason(val value: Int) {
    Motion(0),
  }

  enum class ZoneManagementClusterZoneSource(val value: Int) {
    Mfg(0),
    User(1),
  }

  enum class ZoneManagementClusterZoneType(val value: Int) {
    TwoDCARTZone(0),
  }

  enum class ZoneManagementClusterZoneUse(val value: Int) {
    Motion(0),
    Privacy(1),
    Focus(2),
  }
}
