// SPDX-FileCopyrightText: 2023 Google LLC
// SPDX-License-Identifier: Apache-2.0

package io.aether.android.chip

object MatterConstants {
  val DeviceTypesMap =
      mapOf<Long, String>(
          10L to "Door Lock",
          11L to "Door Lock Controller",
          14L to "Aggregator",
          15L to "Generic Switch",
          17L to "Power Source",
          18L to "OTA Requestor",
          19L to "Bridged Node",
          20L to "OTA Provider",
          21L to "Contact Sensor",
          22L to "Root Node",
          23L to "Solar Power",
          24L to "Battery Storage",
          25L to "Secondary Network Interface",
          34L to "Speaker",
          35L to "Casting Video Player",
          36L to "Content App",
          39L to "Mode Select",
          40L to "Basic Video Player",
          41L to "Casting Video Client",
          42L to "Video Remote Control",
          43L to "Fan",
          44L to "Air Quality Sensor",
          45L to "Air Purifier",
          65L to "Water Freeze Detector",
          66L to "Water Valve",
          67L to "Water Leak Detector",
          68L to "Rain Sensor",
          69L to "Soil Sensor",
          112L to "Refrigerator",
          113L to "Temperature Controlled Cabinet",
          114L to "Room Air Conditioner",
          115L to "Laundry Washer",
          116L to "Robotic Vacuum Cleaner",
          117L to "Dishwasher",
          118L to "Smoke CO Alarm",
          119L to "Cook Surface",
          120L to "Cooktop",
          121L to "Microwave Oven",
          122L to "Extractor Hood",
          123L to "Oven",
          124L to "Laundry Dryer",
          144L to "Network Infrastructure Manager",
          145L to "Thread Border Router",
          256L to "On/Off Light",
          257L to "Dimmable Light",
          259L to "On/Off Light Switch",
          260L to "Dimmer Switch",
          261L to "Color Dimmer Switch",
          262L to "Light Sensor",
          263L to "Occupancy Sensor",
          266L to "On/Off Plug-in Unit",
          267L to "Dimmable Plug-in Unit",
          268L to "Color Temperature Light",
          269L to "Extended Color Light",
          271L to "Mounted On/Off Control",
          272L to "Mounted Dimmable Load Control",
          304L to "Joint Fabric Administrator",
          320L to "Intercom",
          321L to "Audio Doorbell",
          322L to "Camera",
          323L to "Video Doorbell",
          324L to "Floodlight Camera",
          325L to "Snapshot Camera",
          326L to "Chime",
          327L to "Camera Controller",
          328L to "Doorbell",
          336L to "Ambient Context Sensor",
          338L to "Proximity Ranger",
          514L to "Window Covering",
          515L to "Window Covering Controller",
          560L to "Closure",
          561L to "Closure Panel",
          574L to "Closure Controller",
          769L to "Thermostat",
          770L to "Temperature Sensor",
          771L to "Pump",
          772L to "Pump Controller",
          773L to "Pressure Sensor",
          774L to "Flow Sensor",
          775L to "Humidity Sensor",
          777L to "Heat Pump",
          778L to "Thermostat Controller",
          1292L to "EVSE",
          1293L to "Device Energy Management",
          1295L to "Water Heater",
          1296L to "Electrical Sensor",
          1297L to "Electrical Utility Meter",
          1298L to "Meter Reference Point",
          1299L to "Electrical Energy Tariff",
          1300L to "Electrical Meter",
          2112L to "Control Bridge",
          2128L to "On/Off Sensor",
      )

  val ClustersMap =
      mapOf<Long, String>(
          3L to "Identify",
          4L to "Groups",
          5L to "Scenes",
          6L to "On/Off",
          8L to "Level Control",
          28L to "Pulse Width Modulation",
          29L to "Descriptor",
          30L to "Binding",
          31L to "Access Control",
          37L to "Actions",
          40L to "Basic Information",
          41L to "OTA Software Update Provider",
          42L to "OTA Software Update Requestor",
          43L to "Localization Configuration",
          44L to "Time Format Localization",
          45L to "Unit Localization",
          46L to "Power Source Configuration",
          47L to "Power Source",
          48L to "General Commissioning",
          49L to "Network Commissioning",
          50L to "Diagnostic Logs",
          51L to "General Diagnostics",
          52L to "Software Diagnostics",
          53L to "Thread Network Diagnostics",
          54L to "Wi-Fi Network Diagnostics",
          55L to "Ethernet Network Diagnostics",
          56L to "Time Synchronization",
          57L to "Bridged Device Basic Information",
          59L to "Switch",
          60L to "Administrator Commissioning",
          62L to "Node Operational Credentials",
          63L to "Group Key Management",
          64L to "Fixed Label",
          65L to "User Label",
          66L to "Proxy Configuration",
          67L to "Proxy Discovery",
          68L to "Proxy Valid",
          69L to "Boolean State",
          70L to "ICD Management",
          71L to "Timer",
          72L to "Oven Cavity Operational State",
          73L to "Oven Mode",
          74L to "Laundry Dryer Controls",
          80L to "Mode Select",
          81L to "Laundry Washer Mode",
          82L to "Refrigerator And Temperature Controlled Cabinet Mode",
          83L to "Laundry Washer Controls",
          84L to "RVC Run Mode",
          85L to "RVC Clean Mode",
          86L to "Temperature Control",
          87L to "Refrigerator Alarm",
          89L to "Dishwasher Mode",
          91L to "Air Quality",
          92L to "Smoke CO Alarm",
          93L to "Dishwasher Alarm",
          94L to "Microwave Oven Mode",
          95L to "Microwave Oven Control",
          96L to "Operational State",
          97L to "RVC Operational State",
          98L to "Scenes Management",
          101L to "Groupcast",
          113L to "HEPA Filter Monitoring",
          114L to "Activated Carbon Filter Monitoring",
          121L to "Water Tank Level Monitoring",
          128L to "Boolean State Configuration",
          129L to "Valve Configuration And Control",
          144L to "Electrical Power Measurement",
          145L to "Electrical Energy Measurement",
          148L to "Water Heater Management",
          149L to "Commodity Price",
          151L to "Messages",
          152L to "Device Energy Management",
          153L to "Energy EVSE",
          155L to "Energy Preference",
          156L to "Power Topology",
          157L to "Energy EVSE Mode",
          158L to "Water Heater Mode",
          159L to "Device Energy Management Mode",
          160L to "Electrical Grid Conditions",
          257L to "Door Lock",
          258L to "Window Covering",
          260L to "Closure Control",
          261L to "Closure Dimension",
          336L to "Service Area",
          512L to "Pump Configuration And Control",
          513L to "Thermostat",
          514L to "Fan Control",
          516L to "Thermostat User Interface Configuration",
          517L to "Humidistat",
          768L to "Color Control",
          769L to "Ballast Configuration",
          1024L to "Illuminance Measurement",
          1026L to "Temperature Measurement",
          1027L to "Pressure Measurement",
          1028L to "Flow Measurement",
          1029L to "Relative Humidity Measurement",
          1030L to "Occupancy Sensing",
          1036L to "Carbon Monoxide Concentration Measurement",
          1037L to "Carbon Dioxide Concentration Measurement",
          1043L to "Nitrogen Dioxide Concentration Measurement",
          1045L to "Ozone Concentration Measurement",
          1066L to "PM2.5 Concentration Measurement",
          1067L to "Formaldehyde Concentration Measurement",
          1068L to "PM1 Concentration Measurement",
          1069L to "PM10 Concentration Measurement",
          1070L to "Total Volatile Organic Compounds Concentration Measurement",
          1071L to "Radon Concentration Measurement",
          1072L to "Soil Measurement",
          1073L to "Ambient Context Sensing",
          1075L to "Proximity Ranging",
          1104L to "Network Identity Management",
          1105L to "Wi-Fi Network Management",
          1106L to "Thread Border Router Management",
          1107L to "Thread Network Directory",
          1283L to "Wake On Lan",
          1284L to "Channel",
          1285L to "Target Navigator",
          1286L to "Media Playback",
          1287L to "Media Input",
          1288L to "Low Power",
          1289L to "Keypad Input",
          1290L to "Content Launcher",
          1291L to "Audio Output",
          1292L to "Application Launcher",
          1293L to "Application Basic",
          1294L to "Account Login",
          1295L to "Content Control",
          1296L to "Content App Observer",
          1360L to "Zone Management",
          1361L to "Camera AV Stream Management",
          1362L to "Camera AV Settings User Level Management",
          1363L to "WebRTC Transport Provider",
          1364L to "WebRTC Transport Requestor",
          1365L to "Push AV Stream Transport",
          1366L to "Chime",
          1792L to "Commodity Tariff",
          1872L to "Ecosystem Information",
          1873L to "Commissioner Control",
          1874L to "Joint Fabric Datastore",
          1875L to "Joint Fabric Administrator",
          2049L to "TLS Certificate Management",
          2050L to "TLS Client Management",
          2822L to "Meter Identification",
          2823L to "Commodity Metering",
          4294048773L to "Unit Testing",
          4294048774L to "Fault Injection",
          4294048800L to "Sample MEI",
      )

  // Well known cluster attributes
  const val OnOffClusterId = 6L
  const val LevelControlClusterId = 8L
  const val ColorControlClusterId = 768L

  data class ClusterAttribute(val clusterId: Long, val attributeId: Long)

  val OnOffAttribute = ClusterAttribute(OnOffClusterId, 0L)
  val LevelAttribute = ClusterAttribute(LevelControlClusterId, 0L)
  val ColorTemperatureAttribute = ClusterAttribute(ColorControlClusterId, 7L)
}
