#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 The Authors
# SPDX-License-Identifier: Apache-2.0

# Usage:
#   ./matter-data-model-parser.py \
#       --data-model-dir matter-sdk/data_model \
#       --out-proto MatterDataModel.proto \
#       --out-bin-dir app/src/main/assets/matter
#
# The script scans every version sub-directory inside --data-model-dir
# (e.g. 1.0, 1.1, 1.2, ...), collects ALL unique attribute/argument types
# across ALL versions so that the generated MatterType enum stays
# compatible between versions, then writes:
#   - one shared .proto file  (--out-proto)
#   - one binary file per version  (--out-bin-dir/v<ver>.bin)
#
# Dependencies:  pip install lxml protobuf

import os
import re
import glob
import argparse
import importlib
import subprocess
import sys
from pathlib import Path

import lxml.etree as ET


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _clean_type_name(t: str) -> str:
    """Return the UPPER_SNAKE_CASE variant used in the proto enum."""
    return t.upper().replace("-", "_").replace(" ", "_").replace(".", "_")


def _xml_files_for_version(data_model_dir: str, version: str) -> list[str]:
    return glob.glob(
        os.path.join(data_model_dir, version, "**", "*.xml"),
        recursive=True,
    )


# ---------------------------------------------------------------------------
# Pass 1 – collect ALL unique types across ALL versions
# ---------------------------------------------------------------------------


def collect_all_types(data_model_dir: str, versions: list[str]) -> list[str]:
    unique_types: set[str] = set()
    for version in versions:
        for xml_file in _xml_files_for_version(data_model_dir, version):
            tree = ET.parse(xml_file)
            for t in tree.xpath(
                "//attribute/@type | //arg/@type | //item/@type",
            ):
                unique_types.add(_clean_type_name(t.strip()))
    return sorted(filter(None, unique_types))


# ---------------------------------------------------------------------------
# Pass 2 – write the shared .proto file
# ---------------------------------------------------------------------------


def generate_proto_file(
    types: list[str],
    output_proto: str,
    java_package: str = "io.aether.android.matter",
) -> None:
    with open(output_proto, "w") as f:
        f.write(
            "// Auto-generated by matter-data-model-parser.py - do not edit.\n"
            'syntax = "proto3";\n'
            "package matter.data_model;\n\n"
            f'option java_package = "{java_package}";\n'
            "option java_multiple_files = true;\n\n",
        )

        # MatterType enum (union of all types across all versions)
        f.write("enum MatterType {\n  TYPE_UNKNOWN = 0;\n")
        for i, t in enumerate(types, 1):
            f.write(f"  TYPE_{t} = {i};\n")
        f.write("}\n\n")

        # Struct support
        f.write(
            "message StructField {\n"
            "  string name = 1;\n"
            "  MatterType type = 2;\n"
            "}\n\n"
            "message StructDef {\n"
            "  string name = 1;\n"
            "  repeated StructField fields = 2;\n"
            "}\n\n",
        )

        # Core data model messages
        f.write(
            "message Attribute {\n"
            "  uint32 id = 1;\n"
            "  string name = 2;\n"
            "  MatterType type = 3;\n"
            "  bool writable = 4;\n"
            "}\n\n"
            "message Parameter {\n"
            "  string name = 1;\n"
            "  MatterType type = 2;\n"
            "}\n\n"
            "message Command {\n"
            "  uint32 id = 1;\n"
            "  string name = 2;\n"
            "  repeated Parameter parameters = 3;\n"
            "}\n\n"
            "message Cluster {\n"
            "  uint32 id = 1;\n"
            "  string name = 2;\n"
            "  repeated Attribute attributes = 3;\n"
            "  repeated Command commands = 4;\n"
            "}\n\n"
            "message Device {\n"
            "  uint32 id = 1;\n"
            "  string name = 2;\n"
            "  repeated uint32 clusters = 3;\n"
            "}\n\n",
        )

        # Root universe
        f.write(
            "message MatterDataModel {\n"
            "  repeated Device devices = 1;\n"
            "  repeated Cluster clusters = 2;\n"
            "  repeated StructDef structs = 3;\n"
            "}\n",
        )


# ---------------------------------------------------------------------------
# Pass 3 – compile the proto and load the generated Python module
# ---------------------------------------------------------------------------


def compile_proto(proto_file: str):
    subprocess.run(["protoc", "--python_out=.", proto_file], check=True)
    module_name = Path(proto_file).stem.replace("-", "_") + "_pb2"
    sys.path.insert(0, os.getcwd())
    return importlib.import_module(module_name)


# ---------------------------------------------------------------------------
# Pass 4 – populate + serialise one binary file per version
# ---------------------------------------------------------------------------


def populate_binary(
    data_model_dir: str,
    version: str,
    pb2,
    output_bin: str,
) -> None:
    xml_files = _xml_files_for_version(data_model_dir, version)
    universe = pb2.MatterDataModel()

    def get_type_enum(type_str: str):
        if not type_str:
            return pb2.TYPE_UNKNOWN
        clean = "TYPE_" + _clean_type_name(type_str)
        return getattr(pb2, clean, pb2.TYPE_UNKNOWN)

    processed_structs: set[str] = set()

    for xml_file in xml_files:
        tree = ET.parse(xml_file)
        root = tree.getroot()

        # Structs (global)
        for struct in tree.xpath("//struct"):
            s_name = struct.get("name")
            if s_name and s_name not in processed_structs:
                sd = universe.structs.add()
                sd.name = s_name
                for item in struct.xpath("./item"):
                    f = sd.fields.add()
                    f.name = item.get("name", "unknown")
                    f.type = get_type_enum(item.get("type", ""))
                processed_structs.add(s_name)

        # Clusters
        if root.tag == "cluster":
            c = universe.clusters.add()
            c.id = int(root.get("id", "0"), 0)
            c.name = root.get("name", "unknown")
            for attr in root.xpath("//attribute"):
                a = c.attributes.add()
                a.id = int(attr.get("code", "0"), 0)
                a.name = attr.get("name", "")
                a.type = get_type_enum(attr.get("type", ""))
                a.writable = "W" in attr.get("access", "")
            for cmd in root.xpath("//command"):
                co = c.commands.add()
                co.id = int(cmd.get("code", "0"), 0)
                co.name = cmd.get("name", "")
                for arg in cmd.xpath("./arg"):
                    p = co.parameters.add()
                    p.name = arg.get("name", "")
                    p.type = get_type_enum(arg.get("type", ""))

        # Device types
        elif root.tag == "deviceType":
            dt = universe.devices.add()
            dt.id = int(root.get("id", "0"), 0)
            dt.name = root.get("name", "")
            for cl in root.xpath("//clusters/cluster[@usage='mandatory']"):
                dt.clusters.append(int(cl.get("code", "0"), 0))

    with open(output_bin, "wb") as f:
        f.write(universe.SerializeToString())


parser = argparse.ArgumentParser(
    description=(
        "Parse Matter data-model XML files and emit a shared .proto plus "
        "one binary (.bin) file per spec version."
    ),
)
parser.add_argument(
    "--out-proto",
    metavar="FILE",
    default="MatterDataModel.proto",
    help="path to write the generated .proto file; default: %(default)s",
)
parser.add_argument(
    "--out-bin-dir",
    metavar="DIR",
    default="app/src/main/assets/matter",
    help=(
        "directory to write the per-version binary files; "
        "each file is named v<version>.bin; default: %(default)s"
    ),
)
parser.add_argument(
    "DATA_MODEL_DIR",
    help=(
        "top-level Matter data-model directory that contains one "
        "sub-directory per spec version (e.g. matter-sdk/data_model)"
    ),
)

args = parser.parse_args()

versions = []
# Discover version sub-directories (e.g. 1.0, 1.1, 1.2, ...)
for entry in os.scandir(args.DATA_MODEL_DIR):
    if entry.is_dir() and re.match(r"^\d+\.\d+", entry.name):
        versions.append(entry.name)

if not versions:
    print(
        f"ERROR: No version sub-directories found in {args.DATA_MODEL_DIR!r}.",
        file=sys.stderr,
    )
    sys.exit(1)

versions.sort(key=lambda v: [int(x) for x in v.split(".")])
print(f"Found {len(versions)} version(s): {', '.join(versions)}")

# Pass 1 – collect types from ALL versions
print("Collecting unique types across all versions...")
types = collect_all_types(args.DATA_MODEL_DIR, versions)

# Pass 2 – write proto
print(f"Writing {args.out_proto}...")
generate_proto_file(types, args.out_proto)

# Pass 3 – compile proto
print("Compiling proto...")
pb2 = compile_proto(args.out_proto)

# Pass 4 – write one binary per version
os.makedirs(args.out_bin_dir, exist_ok=True)
for version in versions:
    output_bin = os.path.join(args.out_bin_dir, f"v{version}.bin")
    print(f"Writing {output_bin}...")
    populate_binary(args.DATA_MODEL_DIR, version, pb2, output_bin)
