#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 The Authors
# SPDX-License-Identifier: Apache-2.0

# Usage:
#   scripts/matter-data-model-parser.py \
#       --out-proto MatterDataModel.proto \
#       --out-bin-dir app/src/main/assets/matter \
#       matter-sdk/data_model
#
# The script scans every version sub-directory inside Matter SDK data model
# dir (e.g. 1.0, 1.1, 1.2, ...) and collects ALL unique attribute/argument
# types across ALL versions so that the generated MatterType enum stays
# compatible between versions, then writes:
#   - one shared .proto file
#   - one binary file per version
#
# Dependencies:  pip install lxml protobuf

import re
import argparse
import importlib
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

import lxml.etree as ET


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _clean_name(t: str) -> str:
    """Return the UPPER_SNAKE_CASE variant used in the proto enum."""
    # Insert an underscore before any capital letter preceded by a lowercase
    # letter or digit e.g., 'camelCase' -> 'camel_Case'
    s1 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", t)
    # Handle consecutive capitals e.g., 'HTTPResponse' -> 'HTTP_Response'
    s2 = re.sub(r"([A-Z])([A-Z][a-z])", r"\1_\2", s1)
    # Replace other delimiters, capitalize, and clean up multiple/trailing underscores.
    cleaned = s2.replace("-", "_").replace(" ", "_").replace(".", "_").upper()
    return re.sub(r"_+", "_", cleaned).strip("_")


def _get_type(element: ET._Element) -> str:
    """Extract the type from an XML element, handling any special cases."""
    type = _clean_name(element.get("type", "").strip())
    if (
        type == "LIST"
        # For list types, we need to get the element type from the "entry" element.
        and (entry := element.find("./entry")) is not None
        and (entry_type := _get_type(entry))
    ):
        return f"{type}_{entry_type}"
    return type


def _xml_files_for_version(data_model_dir: Path, version: str) -> list[Path]:
    return sorted(data_model_dir.joinpath(version).rglob("**/*.xml"))


# ---------------------------------------------------------------------------
# Pass 1 – collect ALL unique types across ALL versions
# ---------------------------------------------------------------------------


def collect_all_types(data_model_dir: Path, versions: list[str]) -> list[str]:
    """Collect all unique attribute/argument types across ALL versions."""
    # Keep track of how many times each type is used across all versions to
    # compact the generated proto (most common types get lower enum values).
    types: dict[str, int] = defaultdict(int)
    for version in versions:
        for xml_file in _xml_files_for_version(data_model_dir, version):
            tree = ET.parse(xml_file)
            # Iterate over all elements with a "type" attribute.
            for elem in tree.xpath("//*[@type]"):
                if t := _get_type(elem):
                    types[t] += 1
    # Sort by usage count (descending) and then alphabetically
    # for deterministic output, and return just the type names.
    return sorted(types.keys(), key=lambda t: (-types[t], t))


def collect_all_privileges(data_model_dir: Path, versions: list[str]) -> list[str]:
    """Collect all unique privileges across ALL versions."""
    privileges: set[str] = set()
    for version in versions:
        for xml_file in _xml_files_for_version(data_model_dir, version):
            tree = ET.parse(xml_file)
            for p in tree.xpath(
                "|".join(
                    [
                        "//access/@readPrivilege",
                        "//access/@writePrivilege",
                        "//access/@invokePrivilege",
                    ]
                )
            ):
                if p := _clean_name(p.strip()):
                    privileges.add(p)
    return sorted(filter(None, privileges))


# ---------------------------------------------------------------------------
# Pass 2 – write the shared .proto file
# ---------------------------------------------------------------------------


def generate_proto_file(
    types: list[str],
    privileges: list[str],
    output_proto: str,
    java_package: str = "io.aether.android.matter",
) -> None:
    with open(output_proto, "w") as f:
        # Header with license and note about auto-generation.
        spdx = "SPDX"  # Hide code generator from REUSE tool.
        f.write(
            f"// {spdx}-FileCopyrightText: 2026 The Authors\n"
            f"// {spdx}-License-Identifier: Apache-2.0\n"
            "\n"
            "// Auto-generated by matter-data-model-parser.py - do not edit.\n"
            "//\n"
            "// Binary assets under app/src/main/assets/matter/ are generated by\n"
            "// scripts/matter-data-model-parser.py and include various mappings,\n"
            "// command signatures, types and structure definitions. Keep field\n"
            "// numbers in sync with the parser output.\n"
            "\n"
        )

        # Proto syntax and package declaration.
        f.write(
            'syntax = "proto3";\n'
            "package matter.data_model;\n\n"
            f'option java_package = "{java_package}";\n'
            "option java_multiple_files = true;\n\n",
        )

        # MatterType enum (union of all types across all versions)
        f.write("enum MatterType {\n  TYPE_UNKNOWN = 0;\n")
        for i, t in enumerate(types, 1):
            f.write(f"  TYPE_{t} = {i};\n")
        f.write("}\n\n")

        # MatterPrivilege enum (union of all privileges across all versions)
        f.write("enum MatterPrivilege {\n  PRIVILEGE_UNKNOWN = 0;\n")
        for i, p in enumerate(privileges, 1):
            f.write(f"  PRIVILEGE_{p} = {i};\n")
        f.write("}\n\n")

        # Struct support
        f.write(
            "message StructField {\n"
            "  string name = 1;\n"
            "  MatterType type = 2;\n"
            "}\n\n"
            "message StructDef {\n"
            "  string name = 1;\n"
            "  repeated StructField fields = 2;\n"
            "}\n\n",
        )

        # Core data model messages
        f.write(
            "message Attribute {\n"
            "  uint32 id = 1;\n"
            "  string name = 2;\n"
            "  MatterType type = 3;\n"
            "  MatterPrivilege read_privilege = 4;\n"
            "  MatterPrivilege write_privilege = 5;\n"
            "}\n\n"
            "message Parameter {\n"
            "  string name = 1;\n"
            "  MatterType type = 2;\n"
            "}\n\n"
            "message Command {\n"
            "  uint32 id = 1;\n"
            "  string name = 2;\n"
            "  repeated Parameter parameters = 3;\n"
            "}\n\n"
            "message Cluster {\n"
            "  uint32 id = 1;\n"
            "  string name = 2;\n"
            "  repeated Attribute attributes = 3;\n"
            "  repeated Command commands = 4;\n"
            "}\n\n"
            "message Device {\n"
            "  uint32 id = 1;\n"
            "  string name = 2;\n"
            "  repeated uint32 clusters = 3;\n"
            "}\n\n",
        )

        # Root universe
        f.write(
            "message MatterDataModel {\n"
            "  repeated Device devices = 1;\n"
            "  repeated Cluster clusters = 2;\n"
            "  repeated StructDef structs = 3;\n"
            "}\n",
        )


# ---------------------------------------------------------------------------
# Pass 3 – compile the proto and load the generated Python module
# ---------------------------------------------------------------------------


def compile_proto(proto_file: str):
    subprocess.run(["protoc", "--python_out=.", proto_file], check=True)
    module_name = Path(proto_file).stem.replace("-", "_") + "_pb2"
    sys.path.insert(0, str(Path(proto_file).parent.resolve()))
    return importlib.import_module(module_name)


# ---------------------------------------------------------------------------
# Pass 4 – populate + serialize one binary file per version
# ---------------------------------------------------------------------------


def populate_binary(
    data_model_dir: Path,
    version: str,
    pb2,
    output_bin: Path,
) -> None:

    @dataclass
    class DeviceDef:
        id: int
        name: str
        clusters: set[int]

    @dataclass
    class FieldDef:
        id: int
        name: str
        type: str

    @dataclass
    class StructDef:
        name: str
        fields: list[FieldDef]

    @dataclass
    class AttributeDef:
        id: int
        name: str
        type: str
        read_privilege: str = ""
        write_privilege: str = ""

    @dataclass
    class CommandDef:
        id: int
        name: str
        parameters: list[FieldDef]

    @dataclass
    class ClusterDef:
        id: int
        name: str
        attributes: list[AttributeDef]
        commands: list[CommandDef]

    base_device_clusters: set[int] = set()
    devices: dict[int, DeviceDef] = {}
    structs: dict[str, StructDef] = {}
    clusters: dict[int, ClusterDef] = {}

    for xml_file in _xml_files_for_version(data_model_dir, version):
        tree = ET.parse(xml_file)
        root = tree.getroot()

        # Devices
        if root.tag == "deviceType":
            if root.get("name") == "Base Device Type":
                for cl in root.xpath("./clusters/cluster"):
                    base_device_clusters.add(int(cl.get("id"), 0))
                continue
            d = DeviceDef(
                id=int(root.get("id"), 0),
                name=root.get("name"),
                clusters=set(),
            )
            for cl in root.xpath("./clusters/cluster"):
                d.clusters.add(int(cl.get("id"), 0))
            devices[d.id] = d

        # Structs
        for struct in tree.xpath("//struct"):
            s = StructDef(
                name=struct.get("name"),
                fields=[],
            )
            for field in struct.xpath("./field"):
                s.fields.append(
                    FieldDef(
                        id=int(field.get("id"), 0),
                        name=field.get("name"),
                        type=_get_type(field),
                    )
                )
            structs[s.name] = s

        # Clusters
        if root.tag == "cluster":
            # Find all cluster ID entries within the clusterIds container
            for cluster in root.xpath("./clusterIds/clusterId"):
                if not cluster.get("id"):
                    # Skip entries without an ID
                    continue
                c = ClusterDef(
                    id=int(cluster.get("id"), 0),
                    name=cluster.get("name"),
                    attributes=[],
                    commands=[],
                )
                for attr in root.xpath("./attributes/attribute"):
                    c.attributes.append(
                        a := AttributeDef(
                            id=int(attr.get("id"), 0),
                            name=attr.get("name"),
                            type=_get_type(attr),
                        )
                    )
                    if access := attr.xpath("./access"):
                        a.read_privilege = _clean_name(access[0].get("readPrivilege", ""))
                        a.write_privilege = _clean_name(access[0].get("writePrivilege", ""))
                for cmd in root.xpath("./commands/command"):
                    fields = []
                    for field in cmd.xpath("./field"):
                        fields.append(
                            FieldDef(
                                id=int(field.get("id", "0"), 0),
                                name=field.get("name"),
                                type=_get_type(field),
                            )
                        )
                    c.commands.append(
                        CommandDef(
                            id=int(cmd.get("id"), 0),
                            name=cmd.get("name"),
                            parameters=fields,
                        )
                    )
                clusters[c.id] = c

    def get_type_enum(type: str):
        if not type:
            return pb2.TYPE_UNKNOWN
        return getattr(pb2, "TYPE_" + type, pb2.TYPE_UNKNOWN)

    def get_privilege_enum(privilege: str):
        if not privilege:
            return pb2.PRIVILEGE_UNKNOWN
        return getattr(pb2, "PRIVILEGE_" + privilege, pb2.PRIVILEGE_UNKNOWN)

    universe = pb2.MatterDataModel()

    # Add base device clusters to all devices that don't explicitly list them
    for dev in devices.values():
        if not dev.clusters:
            dev.clusters.update(base_device_clusters)

    # Sort devices by ID and clusters by ID for deterministic output
    for dev in sorted(devices.values(), key=lambda x: x.id):
        pb_dev = universe.devices.add()
        pb_dev.id = dev.id
        pb_dev.name = dev.name
        for cluster in sorted(dev.clusters):
            pb_dev.clusters.append(cluster)

    # Sort structs by name for deterministic output
    for struct in sorted(structs.values(), key=lambda x: x.name):
        pb_struct = universe.structs.add()
        pb_struct.name = struct.name
        for field in sorted(struct.fields, key=lambda x: x.id):
            pb_field = pb_struct.fields.add()
            pb_field.type = get_type_enum(field.type)
            pb_field.name = field.name

    # Sort clusters by ID for deterministic output
    for cluster in sorted(clusters.values(), key=lambda x: x.id):
        pb_cluster = universe.clusters.add()
        pb_cluster.id = cluster.id
        pb_cluster.name = cluster.name
        for attr in sorted(cluster.attributes, key=lambda x: x.id):
            pb_attr = pb_cluster.attributes.add()
            pb_attr.id = attr.id
            pb_attr.name = attr.name
            pb_attr.type = get_type_enum(attr.type)
            pb_attr.read_privilege = get_privilege_enum(attr.read_privilege)
            pb_attr.write_privilege = get_privilege_enum(attr.write_privilege)
        for cmd in sorted(cluster.commands, key=lambda x: x.id):
            pb_cmd = pb_cluster.commands.add()
            pb_cmd.id = cmd.id
            pb_cmd.name = cmd.name
            for param in sorted(cmd.parameters, key=lambda x: x.id):
                pb_param = pb_cmd.parameters.add()
                pb_param.type = get_type_enum(param.type)
                pb_param.name = param.name

    with open(output_bin, "wb") as f:
        f.write(universe.SerializeToString())


parser = argparse.ArgumentParser(
    description=(
        "Parse Matter data-model XML files and emit a shared .proto plus "
        "one binary (.bin) file per spec version."
    ),
)
parser.add_argument(
    "--out-proto",
    metavar="FILE",
    type=Path,
    default="MatterDataModel.proto",
    help="path to write the generated .proto file; default: %(default)s",
)
parser.add_argument(
    "--out-bin-dir",
    metavar="DIR",
    type=Path,
    default="app/src/main/assets/matter",
    help=(
        "directory to write the per-version binary files; "
        "each file is named v<version>.bin; default: %(default)s"
    ),
)
parser.add_argument(
    "DATA_MODEL_DIR",
    type=Path,
    help=(
        "top-level Matter data-model directory that contains one "
        "sub-directory per spec version (e.g. matter-sdk/data_model)"
    ),
)

args = parser.parse_args()

versions = []
# Discover version sub-directories (e.g. 1.0, 1.1, 1.2, 1.2.1, etc.)
for entry in args.DATA_MODEL_DIR.iterdir():
    if entry.is_dir() and re.match(r"^\d+\.\d+", entry.name):
        versions.append(entry.name)

if not versions:
    print(f"ERROR: No version sub-directories found in {args.DATA_MODEL_DIR}", file=sys.stderr)
    sys.exit(1)

versions.sort(key=lambda v: [int(x) for x in v.split(".")])
print(f"Found {len(versions)} version(s): {', '.join(versions)}")

# Pass 1 – collect types from ALL versions
print("Collecting unique types across all versions...")
types = collect_all_types(args.DATA_MODEL_DIR, versions)
print("Collecting unique privileges across all versions...")
privileges = collect_all_privileges(args.DATA_MODEL_DIR, versions)

# Pass 2 – write proto
print(f"Writing {args.out_proto}...")
generate_proto_file(types, privileges, args.out_proto)

# Pass 3 – compile proto
print("Compiling proto...")
pb2 = compile_proto(args.out_proto)

# Pass 4 – write one binary per version
args.out_bin_dir.mkdir(parents=True, exist_ok=True)
for version in versions:
    output_bin = args.out_bin_dir / f"v{version}.bin"
    print(f"Writing {output_bin}...")
    populate_binary(args.DATA_MODEL_DIR, version, pb2, output_bin)
